# Generated by Django 5.2.12 on 2026-03-26 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer_app', '0007_remove_collaborativeedit_manuscript_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='Users who can collaborate on this manuscript', related_name='collaborated_manuscripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CollaborationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invited_email', models.EmailField(blank=True, help_text='For inviting users not yet registered', max_length=254)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='editor', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Optional invitation message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_collaboration_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_collaboration_invites', to=settings.AUTH_USER_MODEL)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='writer_app.manuscript')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['manuscript', 'status'], name='writer_app__manuscr_7a7459_idx'), models.Index(fields=['invited_user', 'status'], name='writer_app__invited_5b1353_idx')],
                'unique_together': {('manuscript', 'invited_email'), ('manuscript', 'invited_user')},
            },
        ),
        migrations.CreateModel(
            name='CollaborativeEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_id', models.CharField(max_length=100)),
                ('operation_type', models.CharField(choices=[('insert', 'Insert'), ('delete', 'Delete'), ('retain', 'Retain')], max_length=20)),
                ('operation_data', models.JSONField()),
                ('version', models.IntegerField()),
                ('client_version', models.IntegerField()),
                ('was_transformed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborative_edits', to='writer_app.manuscript')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='writer_app.collaborativesession')),
            ],
            options={
                'ordering': ['version'],
                'indexes': [models.Index(fields=['manuscript', 'section_id', 'version'], name='writer_app__manuscr_98b4a0_idx'), models.Index(fields=['session', 'created_at'], name='writer_app__session_5175fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(help_text="Which .tex section this comment targets (e.g. 'manuscript/methods')", max_length=200)),
                ('line_start', models.IntegerField(help_text='Starting line number in the section')),
                ('line_end', models.IntegerField(help_text='Ending line number in the section')),
                ('text', models.TextField(help_text='Comment content')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text='Current status of this comment thread', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who wrote this comment', on_delete=django.db.models.deletion.CASCADE, related_name='writer_comments', to=settings.AUTH_USER_MODEL)),
                ('manuscript', models.ForeignKey(help_text='Manuscript this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='writer_app.manuscript')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for reply threads (null for top-level comments)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='writer_app.comment')),
            ],
            options={
                'ordering': ['section_id', 'line_start', '-created_at'],
                'indexes': [models.Index(fields=['manuscript', 'section_id'], name='writer_app__manuscr_07dc84_idx'), models.Index(fields=['manuscript', 'status'], name='writer_app__manuscr_573cf2_idx'), models.Index(fields=['parent'], name='writer_app__parent__01d7a8_idx')],
            },
        ),
    ]
