# Generated by Django 6.0.8 on 2026-08-30 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0040_default_project_names_the_demo'),
        ('writer_app', '0010_add_comment_anchor_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField(help_text='Path relative to the project root')),
                ('file_name', models.TextField()),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(db_index=True, max_length=32)),
                ('last_modified', models.FloatField(default=0.0)),
                ('thumbnail_path', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_referenced', models.BooleanField(db_index=True, default=False)),
                ('reference_count', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('location', models.TextField(blank=True, default='')),
                ('indexed_at', models.FloatField(default=0.0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_figures', to='project_app.project')),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFigureLatexReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tex_file', models.TextField()),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latex_references', to='writer_app.projectfigure')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField(help_text='Path relative to the project root')),
                ('file_name', models.TextField()),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('file_size', models.BigIntegerField(default=0)),
                ('caption', models.TextField(blank=True, default='')),
                ('last_modified', models.FloatField(default=0.0)),
                ('thumbnail_path', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_referenced', models.BooleanField(db_index=True, default=False)),
                ('reference_count', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('location', models.TextField(blank=True, default='')),
                ('indexed_at', models.FloatField(default=0.0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_tables', to='project_app.project')),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
        migrations.AddIndex(
            model_name='projectfigure',
            index=models.Index(fields=['project', 'last_modified'], name='writer_app__project_0b8378_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfigure',
            index=models.Index(fields=['project', 'file_hash'], name='writer_app__project_9ed9dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectfigure',
            constraint=models.UniqueConstraint(fields=('project', 'file_path'), name='uniq_writer_projectfigure_project_filepath'),
        ),
        migrations.AddIndex(
            model_name='projectfigurelatexreference',
            index=models.Index(fields=['figure'], name='writer_app__figure__3b5893_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttable',
            index=models.Index(fields=['project', 'last_modified'], name='writer_app__project_5165d5_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttable',
            index=models.Index(fields=['project', 'file_hash'], name='writer_app__project_51095e_idx'),
        ),
        migrations.AddConstraint(
            model_name='projecttable',
            constraint=models.UniqueConstraint(fields=('project', 'file_path'), name='uniq_writer_projecttable_project_filepath'),
        ),
    ]
