# Generated by Django 5.2.7 on 2025-12-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholar_app", "0015_add_content_hash_to_bibtex_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="search_limits",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="User-specific search limits: {'pubmed': 20, 'arxiv': 25, 'scitex_crossref': 2000, etc.}",
            ),
        ),
    ]
