# Generated by Django 5.2.11 on 2026-02-19 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholar_app", "0017_add_user_library_storage_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreference",
            name="search_limits",
        ),
    ]
