# Generated by Django 5.2.11 on 2026-02-22 01:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0025_add_issue_template"),
        ("scholar_app", "0018_remove_search_limits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedGraph",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("dois", "DOI List"),
                            ("query", "Search Query"),
                            ("library", "Library Papers"),
                        ],
                        default="dois",
                        max_length=10,
                    ),
                ),
                ("seed_dois", models.JSONField(blank=True, default=list)),
                (
                    "query_text",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("build_params", models.JSONField(blank=True, default=dict)),
                ("graph_data", models.JSONField(default=dict)),
                ("node_positions", models.JSONField(blank=True, default=dict)),
                ("node_count", models.IntegerField(default=0)),
                ("edge_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_graphs",
                        to="project_app.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_graphs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-updated_at"],
                        name="scholar_app_user_id_850307_idx",
                    )
                ],
                "unique_together": {("user", "name")},
            },
        ),
    ]
