# Generated by Django 6.0.9 on 2026-10-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_app', '0019_savedgraph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchFilter',
        ),
    ]
