# Generated by Django 5.2.11 on 2026-02-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_app", "0007_workspacesshkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="unix_gid",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Linux GID for OS-level process isolation (same as unix_uid)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="unix_uid",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Linux UID for OS-level process isolation (100000 + user.pk)",
                null=True,
                unique=True,
            ),
        ),
    ]
