# Generated by Django 5.2.11 on 2026-02-20 19:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_name",
                    models.CharField(
                        db_index=True,
                        help_text="Matches ModuleConfig.name in registry.py",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("short_description", models.CharField(blank=True, max_length=200)),
                ("long_description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("writing", "Writing"),
                            ("visualization", "Visualization"),
                            ("data", "Data"),
                            ("analysis", "Analysis"),
                            ("reference", "Reference"),
                            ("utility", "Utility"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("homepage_url", models.URLField(blank=True)),
                ("repository_url", models.URLField(blank=True)),
                ("install_count", models.PositiveIntegerField(default=0)),
                ("star_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=2),
                ),
                (
                    "is_builtin",
                    models.BooleanField(
                        default=False,
                        help_text="Built-in modules cannot be fully uninstalled, only disabled.",
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("unlisted", "Unlisted")],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_modules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace Module",
                "ordering": ["-star_count", "-install_count"],
            },
        ),
        migrations.CreateModel(
            name="ModuleInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("tab_order", models.IntegerField(default=50)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="apps_app.marketplacemodule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installed_modules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Installation",
                "ordering": ["tab_order"],
                "unique_together": {("user", "module")},
            },
        ),
        migrations.CreateModel(
            name="ModuleReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField(blank=True)),
                ("is_from_installer", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="apps_app.marketplacemodule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Review",
                "ordering": ["-created_at"],
                "unique_together": {("user", "module")},
            },
        ),
        migrations.CreateModel(
            name="ModuleStar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stars_rel",
                        to="apps_app.marketplacemodule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starred_modules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-starred_at"],
                "unique_together": {("user", "module")},
            },
        ),
        migrations.CreateModel(
            name="ModuleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("changelog", models.TextField(blank=True)),
                ("min_scitex_version", models.CharField(blank=True, max_length=20)),
                ("is_stable", models.BooleanField(default=True)),
                ("released_at", models.DateTimeField(auto_now_add=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="apps_app.marketplacemodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Version",
                "ordering": ["-released_at"],
                "unique_together": {("module", "version")},
            },
        ),
    ]
