# Generated by Django 5.2.11 on 2026-02-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplacemodule",
            name="status",
            field=models.CharField(
                choices=[
                    ("stable", "Stable"),
                    ("wip", "WIP"),
                    ("beta", "Beta"),
                    ("deprecated", "Deprecated"),
                ],
                default="stable",
                help_text="Development status: stable, wip, beta, deprecated.",
                max_length=15,
            ),
        ),
    ]
