# Generated by Django 5.2.11 on 2026-02-27 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace_app", "0003_alter_marketplacemodule_visibility_modulesubmission"),
        ("project_app", "0027_project_app_category_project_app_license_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marketplacemodule",
            options={
                "ordering": ["-star_count", "-install_count"],
                "verbose_name": "Marketplace App",
            },
        ),
        migrations.AlterModelOptions(
            name="moduleinstallation",
            options={"ordering": ["tab_order"], "verbose_name": "App Installation"},
        ),
        migrations.AlterModelOptions(
            name="modulereview",
            options={"ordering": ["-created_at"], "verbose_name": "App Review"},
        ),
        migrations.AlterModelOptions(
            name="modulesubmission",
            options={"ordering": ["-submitted_at"], "verbose_name": "App Submission"},
        ),
        migrations.AlterModelOptions(
            name="moduleversion",
            options={"ordering": ["-released_at"], "verbose_name": "App Version"},
        ),
        migrations.AddField(
            model_name="marketplacemodule",
            name="project",
            field=models.OneToOneField(
                blank=True,
                help_text="Source project (for user-submitted apps)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marketplace_module",
                to="project_app.project",
            ),
        ),
    ]
