# Generated by Django 5.2.11 on 2026-03-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_app", "0009_alter_modulesubmission_status_appsmodule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulesubmission",
            name="pr_url",
            field=models.URLField(
                blank=True,
                help_text="PR URL on the central registry repo (set on submission)",
            ),
        ),
    ]
