# Generated by Django 5.2.12 on 2026-03-04 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_app", "0010_add_pr_url_to_modulesubmission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DevInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_owner",
                    models.CharField(
                        help_text="Gitea username of repo owner", max_length=150
                    ),
                ),
                (
                    "source_repo",
                    models.CharField(help_text="Gitea repo slug", max_length=200),
                ),
                (
                    "module_name",
                    models.CharField(help_text="dev__<owner>__<repo>", max_length=100),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
                (
                    "icon",
                    models.CharField(default="fas fa-puzzle-piece", max_length=100),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("is_enabled", models.BooleanField(default=True)),
                ("tab_order", models.IntegerField(default=95)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dev_installations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dev Installation",
                "db_table": "marketplace_app_devinstallation",
                "ordering": ["tab_order"],
                "unique_together": {("user", "source_owner", "source_repo")},
            },
        ),
    ]
