# Generated by Django 5.2.12 on 2026-03-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_app", "0011_add_devinstallation"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsmodule",
            name="registry_repo_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL of the canonical fork under scitex-apps org",
            ),
        ),
    ]
