# Generated by Django 5.2.7 on 2025-12-16 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vis_app", "0004_pltz_figz_bundles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStylePreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Preset name (e.g., 'Nature Style', 'My Thesis')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this style preset",
                    ),
                ),
                (
                    "style_config",
                    models.JSONField(
                        default=dict,
                        help_text="SCITEX_STYLE overrides in YAML-compatible format",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the currently active preset",
                    ),
                ),
                (
                    "is_builtin",
                    models.BooleanField(
                        default=False,
                        help_text="Built-in preset (e.g., SciTeX Default)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "-is_builtin", "name"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
