#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Sample content laid onto a new "SciTeX Minimal" project.

A Minimal clone holds only ``.scitex/`` stubs, so a first-time user opens an
empty tree, an empty FigRecipe list and a "Replace this text" abstract. This
adds a tiny dataset, a FigRecipe recipe generated by figrecipe itself, a real
abstract and three classic references.
"""

import logging
import shutil
from pathlib import Path

from ..writer_workspace_layout import WRITER_WORKSPACE_RELPATH

logger = logging.getLogger(__name__)

PAYLOAD_ROOT = Path(__file__).resolve().parent / "payload"
PROJECT_PAYLOAD_DIR = PAYLOAD_ROOT / "project"
WRITER_PAYLOAD_DIR = PAYLOAD_ROOT / "writer"
REFERENCES_RELPATH = "references.bib"
WRITER_BIBLIOGRAPHY_RELPATH = "00_shared/bib_files/bibliography.bib"

SAMPLE_RELPATHS = (
    "data/sample.csv",
    "figures/sample_plot.yaml",
    REFERENCES_RELPATH,
)


def _copy_missing_files(source: Path, destination: Path) -> list[Path]:
    written = []
    for item in sorted(source.rglob("*")):
        target = destination / item.relative_to(source)
        # Never overwrite a user's file; a re-run only fills gaps.
        if item.is_dir() or target.exists():
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(item, target)
        written.append(target)
    return written


def _append_references_to_writer_bibliography(writer_dir: Path) -> None:
    bibliography = writer_dir / WRITER_BIBLIOGRAPHY_RELPATH
    if not bibliography.is_file():
        return
    references = (PROJECT_PAYLOAD_DIR / REFERENCES_RELPATH).read_text(encoding="utf-8")
    existing = bibliography.read_text(encoding="utf-8")
    if "pearson_1901_closest_fit" in existing:
        return
    bibliography.write_text(existing.rstrip("\n") + "\n\n" + references, encoding="utf-8")


def _replace_placeholder_abstract(writer_dir: Path) -> None:
    abstract_relpath = "01_manuscript/contents/abstract.tex"
    abstract = writer_dir / abstract_relpath
    # Only the untouched template stub is replaced, never a user's own abstract.
    if abstract.is_file() and "Replace this text" not in abstract.read_text(encoding="utf-8"):
        return
    abstract.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(WRITER_PAYLOAD_DIR / abstract_relpath, abstract)


def seed_first_project_samples(project_path) -> list[Path]:
    """Write the sample dataset, figure recipe, abstract and references."""
    project_path = Path(project_path)
    written = _copy_missing_files(PROJECT_PAYLOAD_DIR, project_path)
    writer_dir = project_path / WRITER_WORKSPACE_RELPATH
    if writer_dir.is_dir():
        _replace_placeholder_abstract(writer_dir)
        _append_references_to_writer_bibliography(writer_dir)
    logger.info(f"Seeded first-project samples into {project_path} ({len(written)} files)")
    return written


def try_seed_first_project_samples(project_path) -> bool:
    """Seed, logging instead of raising: samples must never fail project creation."""
    try:
        seed_first_project_samples(project_path)
        return True
    except Exception as exc:
        logger.error(f"First-project sample seeding failed for {project_path}: {exc}", exc_info=True)
        return False


# EOF
