# Generated by Django 5.2.7 on 2025-12-15 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vis_app", "0003_figureversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FigzBundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Figure title", max_length=200)),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier", max_length=200),
                ),
                (
                    "bundle_path",
                    models.CharField(
                        help_text="Path to .figz.d directory or .figz ZIP file",
                        max_length=500,
                    ),
                ),
                (
                    "is_zip",
                    models.BooleanField(
                        default=False,
                        help_text="True if stored as ZIP, False if directory",
                    ),
                ),
                (
                    "spec",
                    models.JSONField(
                        default=dict, help_text="FigureSpec: figure_id, layout, panels"
                    ),
                ),
                (
                    "style",
                    models.JSONField(
                        default=dict, help_text="FigureStyle: theme, fonts, spacing"
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("1x1", "Single Panel"),
                            ("2x1", "Two Horizontal"),
                            ("1x2", "Two Vertical"),
                            ("2x2", "Four Panel Grid"),
                            ("1x3", "Three Horizontal"),
                            ("3x1", "Three Vertical"),
                            ("2x3", "Six Panel Grid"),
                            ("custom", "Custom Layout"),
                        ],
                        default="1x1",
                        max_length=20,
                    ),
                ),
                (
                    "width_mm",
                    models.FloatField(default=170.0, help_text="Figure width in mm"),
                ),
                (
                    "height_mm",
                    models.FloatField(
                        blank=True,
                        help_text="Figure height in mm (auto if null)",
                        null=True,
                    ),
                ),
                ("dpi", models.IntegerField(default=300)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "journal_preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="figz_bundles",
                        to="vis_app.journalpreset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="figz_bundles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Figure Bundle",
                "verbose_name_plural": "Figure Bundles",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PltzBundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the plot", max_length=200
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier", max_length=200),
                ),
                (
                    "bundle_path",
                    models.CharField(
                        help_text="Path to .pltz.d directory or .pltz ZIP file",
                        max_length=500,
                    ),
                ),
                (
                    "is_zip",
                    models.BooleanField(
                        default=False,
                        help_text="True if stored as ZIP, False if directory",
                    ),
                ),
                (
                    "spec",
                    models.JSONField(
                        default=dict, help_text="PltzSpec: plot_id, data, axes, traces"
                    ),
                ),
                (
                    "style",
                    models.JSONField(
                        default=dict,
                        help_text="PltzStyle: theme, size, font, traces, legend",
                    ),
                ),
                (
                    "data_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 hash of data.csv for integrity verification",
                        max_length=64,
                    ),
                ),
                (
                    "data_format",
                    models.CharField(
                        default="wide",
                        help_text="Data format: 'wide' or 'long'",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("line", "Line Plots"),
                            ("scatter", "Scatter Plots"),
                            ("bar", "Bar Charts"),
                            ("distribution", "Distributions"),
                            ("statistical", "Statistical"),
                            ("heatmap", "Heatmaps"),
                            ("contour", "Contours"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="List of tags for filtering"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pltz_bundles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FigzPanel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("A", "Panel A"),
                            ("B", "Panel B"),
                            ("C", "Panel C"),
                            ("D", "Panel D"),
                            ("E", "Panel E"),
                            ("F", "Panel F"),
                            ("G", "Panel G"),
                            ("H", "Panel H"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Panel order in layout"),
                ),
                ("x", models.FloatField(default=0.0, help_text="X position (0-1)")),
                ("y", models.FloatField(default=0.0, help_text="Y position (0-1)")),
                ("width", models.FloatField(default=1.0, help_text="Width (0-1)")),
                ("height", models.FloatField(default=1.0, help_text="Height (0-1)")),
                (
                    "style_overrides",
                    models.JSONField(
                        default=dict, help_text="Style overrides for this panel only"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "figure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="figz_panels",
                        to="vis_app.figzbundle",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_usages",
                        to="vis_app.pltzbundle",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "label"],
            },
        ),
        migrations.AddField(
            model_name="figzbundle",
            name="panels",
            field=models.ManyToManyField(
                help_text="Plot bundles used as panels in this figure",
                related_name="parent_figures",
                through="vis_app.FigzPanel",
                to="vis_app.pltzbundle",
            ),
        ),
        migrations.AddIndex(
            model_name="pltzbundle",
            index=models.Index(
                fields=["owner", "category"], name="vis_app_plt_owner_i_aaca12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pltzbundle",
            index=models.Index(
                fields=["data_hash"], name="vis_app_plt_data_ha_cd453e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pltzbundle",
            unique_together={("owner", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="figzpanel",
            unique_together={("figure", "label")},
        ),
        migrations.AlterUniqueTogether(
            name="figzbundle",
            unique_together={("owner", "slug")},
        ),
    ]
