# Generated by Django 5.2.12 on 2026-03-17 11:34
#
# Drop all ORM models from figrecipe_app.
# The React editor uses file-based storage via figrecipe._django,
# not Django ORM models. Alpha stage -- DB can be freely modified.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vis_app", "0005_userstylepreset"),
    ]

    operations = [
        # Delete child models first (FK dependencies)
        migrations.DeleteModel(name="Annotation"),
        migrations.DeleteModel(name="FigurePanel"),
        migrations.DeleteModel(name="FigureVersion"),
        migrations.DeleteModel(name="FigureExport"),
        migrations.DeleteModel(name="ScientificFigure"),
        migrations.DeleteModel(name="FigzPanel"),
        migrations.DeleteModel(name="FigzBundle"),
        migrations.DeleteModel(name="PltzBundle"),
        migrations.DeleteModel(name="JournalPreset"),
        migrations.DeleteModel(name="UserStylePreset"),
    ]
