# Generated by Django 5.2.10 on 2026-01-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Organization avatar/logo', null=True, upload_to='organization_avatars/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, help_text="URL-friendly identifier (e.g., 'scitex-ai')", max_length=100, null=True, unique=True),
        ),
    ]
