# Generated by Django 5.2.11 on 2026-02-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_app", "0002_remove_default_rate_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmconnection",
            name="daily_cost_limit_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Maximum cost in USD per day (empty = unlimited)",
                max_digits=8,
                null=True,
            ),
        ),
    ]
