# Generated by Django 5.2.11 on 2026-02-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnection',
            name='service',
            field=models.CharField(choices=[('orcid', 'ORCID'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('zotero', 'Zotero'), ('overleaf', 'Overleaf'), ('slack', 'Slack'), ('discord', 'Discord'), ('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)'), ('local_llm', 'Local LLM (Ollama/LM Studio)')], max_length=20),
        ),
    ]
