# Generated by Django 5.2.11 on 2026-02-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations_app", "0003_add_event_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationconnection",
            name="service",
            field=models.CharField(
                choices=[
                    ("orcid", "ORCID"),
                    ("github", "GitHub"),
                    ("gitlab", "GitLab"),
                    ("zotero", "Zotero"),
                    ("overleaf", "Overleaf"),
                    ("slack", "Slack"),
                    ("discord", "Discord"),
                    ("anthropic", "Anthropic (Claude)"),
                    ("openai", "OpenAI (GPT)"),
                    ("gemini", "Google (Gemini)"),
                    ("mistral", "Mistral AI"),
                    ("xai", "xAI (Grok)"),
                    ("deepseek", "DeepSeek"),
                    ("openrouter", "OpenRouter"),
                    ("ollama", "Ollama (local)"),
                    ("local_llm", "Local LLM (Ollama/LM Studio)"),
                ],
                max_length=20,
            ),
        ),
    ]
