# Generated by Django 5.2.10 on 2026-02-01 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0024_visitorallocation_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Bug Report')", max_length=100)),
                ('description', models.CharField(blank=True, help_text='Short description shown in template selector', max_length=255)),
                ('template_type', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('docs', 'Documentation Issue'), ('question', 'Question'), ('custom', 'Custom')], default='custom', help_text='Template type for default styling', max_length=20)),
                ('icon', models.CharField(default='fa-file-alt', help_text="FontAwesome icon class (e.g., 'fa-bug', 'fa-lightbulb')", max_length=50)),
                ('title_prefix', models.CharField(blank=True, help_text="Prefix for issue title (e.g., '[BUG]', '[FEATURE]')", max_length=50)),
                ('body_template', models.TextField(blank=True, help_text='Markdown template for issue body')),
                ('order', models.IntegerField(default=0, help_text='Display order in selector')),
                ('is_active', models.BooleanField(default=True, help_text='Show in template selector')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labels', models.ManyToManyField(blank=True, help_text='Labels to auto-apply when using this template', related_name='templates', to='project_app.issuelabel')),
                ('project', models.ForeignKey(help_text='Project this template belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='issue_templates', to='project_app.project')),
            ],
            options={
                'verbose_name': 'Issue Template',
                'verbose_name_plural': 'Issue Templates',
                'ordering': ['order', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
