# Generated by Django 5.2.11 on 2026-02-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0028_add_trip_project_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="app_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="App category for marketplace listing",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="app_license",
            field=models.CharField(
                blank=True,
                default="AGPL-3.0",
                help_text="SPDX license identifier for app distribution",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="app_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                help_text="Marketplace submission status",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_app",
            field=models.BooleanField(
                default=False, help_text="Whether this project is a SciTeX app plugin"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("local", "Local Repository"),
                    ("remote", "Remote Filesystem"),
                    ("trip", "Remote TRIP"),
                ],
                default="local",
                help_text="Local (Git-enabled) or Remote (SSH mount, no Git)",
                max_length=20,
            ),
        ),
    ]
