# Generated by Django 5.2.11 on 2026-03-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0029_make_app_fields_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="topics",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated topic tags (e.g., python,machine-learning,statistics)",
                max_length=500,
            ),
        ),
    ]
