# Generated by Django 5.2.12 on 2026-03-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_app", "0031_rename_home_to_dotfiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="is_home",
            field=models.BooleanField(
                default=False,
                help_text="Dotfiles project: persistent, always private, cannot be deleted",
            ),
        ),
    ]
