# Generated by Django 5.2.12 on 2026-03-09 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_app', '0002_add_organization_slug'),
        ('project_app', '0032_alter_project_is_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='org_owner',
            field=models.ForeignKey(blank=True, help_text='Organization owner (if org-owned project)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='organizations_app.organization'),
        ),
    ]
