# Generated by Django 5.2.12 on 2026-03-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0033_add_org_owner_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteprojectconfig',
            name='connection_mode',
            field=models.CharField(choices=[('trip', 'TRIP (on-demand SSH)'), ('sshfs', 'SSHFS (persistent mount)')], default='trip', help_text='trip = on-demand SSH/SFTP (like TRAMP), sshfs = persistent fuse mount', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('local', 'Local Repository'), ('remote', 'Remote (HPC / Server)')], default='local', help_text='Local (Git-enabled) or Remote (SSH mount, no Git)', max_length=20),
        ),
    ]
