# Generated by Django 6.1 on 2026-08-14 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_add_login_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Normalised (lowercased) verified address. UNIQUE — this is the account key; the constraint is what makes 'one address, one human' true rather than merely intended.", max_length=254, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The human this address identifies.', on_delete=django.db.models.deletion.CASCADE, related_name='verified_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verified email',
                'verbose_name_plural': 'verified emails',
            },
        ),
        migrations.CreateModel(
            name='LinkedIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(help_text='OIDC issuer, e.g. https://accounts.google.com. An IDENTITY KEY: changing a stored value re-keys the row and splits the user.', max_length=255)),
                ('subject', models.CharField(help_text="OIDC subject ('sub'), unique only within its issuer.", max_length=255)),
                ('cards_user_id', models.CharField(blank=True, default='', help_text="The 'u_*' id of this human's record in the scitex-cards user registry. Blank until the board-side upsert succeeds; the write is deliberately allowed to fail without failing the login.", max_length=64)),
                ('host_at_name', models.CharField(blank=True, default='', help_text="Instance namespacing ('host@name'), so two scitex.ai instances sharing a cards store do not collide.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_identities', to=settings.AUTH_USER_MODEL)),
                ('verified_email', models.ForeignKey(blank=True, help_text='The verified address this login carried, when it carried one. NULL is a real state, not a gap: ORCID commonly returns no email at all, and such a login is still a valid identity — it just cannot be used to key or link an account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identities', to='auth_app.verifiedemail')),
            ],
            options={
                'verbose_name': 'linked identity',
                'verbose_name_plural': 'linked identities',
            },
        ),
        migrations.AddIndex(
            model_name='verifiedemail',
            index=models.Index(fields=['user'], name='auth_app_ve_user_id_0307f6_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedidentity',
            index=models.Index(fields=['user'], name='auth_app_li_user_id_3c382b_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedidentity',
            index=models.Index(fields=['cards_user_id'], name='auth_app_li_cards_u_5b3a1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='linkedidentity',
            constraint=models.UniqueConstraint(fields=('issuer', 'subject'), name='uniq_linked_identity_issuer_subject'),
        ),
    ]
