# Generated by Django 6.0.8 on 2026-09-11 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_verifiedemail_linkedidentity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=32)),
                ('content_hash', models.CharField(max_length=64)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at', '-id'],
                'indexes': [models.Index(fields=['user', 'document', 'accepted_at'], name='authapp_cons_user_doc_ts_idx')],
            },
        ),
    ]
