# Generated by Django 5.2.17 on 2026-09-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0011_onboarding_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingsignup",
            name="plan",
            # max_length=32, not 16: the default "subscription-free" is 19
            # chars and Postgres rejects the DDL otherwise (0013 widens to
            # 32 anyway; fresh-Postgres E2E never gets past this step).
            field=models.CharField(default="subscription-free", max_length=32),
        ),
    ]
