# Generated by Django 6.0.8 on 2026-09-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_onboarding_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsignup',
            name='plan',
            field=models.CharField(choices=[('free', 'Free tier'), ('trial', 'Paid trial')], default='trial', max_length=16),
        ),
    ]
