# Generated by Django 5.2.17 on 2026-09-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0012_pendingsignup_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingsignup",
            name="plan",
            field=models.CharField(default="subscription-free", max_length=32),
        ),
    ]
