"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-cloud' references
in its source tree. Renames or moves in peer standalones (or in the
umbrella's deep-import surface) surface as a hard failure here — not
as a silent ModuleNotFoundError when an end user runs the CLI.
"""
import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    'scitex.cli.introspect',
    'scitex_app.appmaker',
    'scitex_app.appmaker._license',
    'scitex_app.appmaker._publish',
    'scitex_app.appmaker._validate',
    'scitex_app.sdk',
    'scitex_app.sdk._client',
    'scitex_config._ecosystem',
    'scitex_dev',
    'scitex_dev._cli._completion',
    'scitex_dev.cli',
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import(module_name):
    """Importing scitex-cloud's declared cross-package dependency must succeed."""
    importlib.import_module(module_name)
