"""Cross-package import gate (PS-140) for scitex-hub.

Every module listed here is imported by this package's source but
OWNED by a peer standalone. A rename or move on the other side of
that boundary is invisible to this package's unit tests and
surfaces as ModuleNotFoundError in a user's process — which is how
the `scitex_io._load_cache` rename went undetected for weeks.

Generated by `scitex-dev ecosystem install-cross-package-gate`.

generated-by: scitex-dev 0.60.2.dev24+g2a69ecff9

A GATE NOBODY CAN DATE IS A CLAIM ABOUT AN UNKNOWN PAST. This
list is a snapshot of the cross-package imports as they stood
when the stamp above was written; it does not update itself, and
a stale copy looks exactly like a current one. Measured
2026-08-16: 17 gates across the fleet carried NO stamp and named
a generator that never existed as a command -- the real writer
was a one-shot script since deleted -- so the only way to tell a
fossil from a live gate was a filesystem sweep of mtimes. The
same disease had already been found in the audit gate (68 of 70
still calling audit_all_for_package() with no path=), and the
same cure applies: say which version wrote you.

Regenerate with:

    scitex-dev ecosystem install-cross-package-gate scitex-hub --force

Do not hand-edit the list: the PS-140 auditor recomputes it from
source on every run and fails on any drift in either direction
(a missing entry OR a stale one).

Hand-written cases go BELOW the second sentinel. Everything there
is preserved byte-identically across regeneration; everything
between the sentinels is overwritten.
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    'scitex.cli.introspect',
    'scitex_app.appmaker',
    'scitex_app.appmaker._license',
    'scitex_app.appmaker._publish',
    'scitex_app.appmaker._validate',
    'scitex_app.sdk',
    'scitex_app.sdk._client',
    'scitex_config._ecosystem',
    'scitex_dev',
    'scitex_dev._cli._completion',
    'scitex_dev.cli',
    'scitex_dev.ecosystem',
    'scitex_dev.jobs',
    'scitex_dev.jobs._placement',
    'scitex_logging',
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import(module_name):
    """Importing scitex-hub's declared cross-package dependency must succeed."""
    # Arrange — skip on the ROOT package only.
    #
    # PS-140. Until this fix the gate called `pytest.importorskip()` on the
    # FULL dotted path, which made it report green on the one failure it
    # exists to catch: a renamed submodule raises ModuleNotFoundError,
    # importorskip swallows it as "peer not installed", and the run is
    # GREEN. The module docstring above already promises the opposite —
    # "Module installed BUT import fails (e.g. internal rename ...) → test
    # FAILS loudly" — so the code contradicted its own stated contract.
    #
    # The root import is the honest "is this peer installed at all?"
    # question, and it is the only part that may legitimately be absent (an
    # optional extra, or a marker-gated dependency, in a lean install).
    pytest.importorskip(module_name.split(".")[0])
    # Act — hard import of the FULL path, so a rename FAILS instead of skipping.
    module = importlib.import_module(module_name)
    # Assert
    assert module.__name__ == module_name
