# Generated by Django 5.2.11 on 2026-02-10 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations_app', '0002_alter_integrationconnection_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_model', models.CharField(blank=True, help_text='Default model identifier (e.g., claude-sonnet-4-5-20250929)', max_length=100)),
                ('total_tokens_used', models.BigIntegerField(default=0, help_text='Total tokens consumed across all requests')),
                ('total_requests', models.IntegerField(default=0, help_text='Total number of API requests made')),
                ('last_request_at', models.DateTimeField(blank=True, null=True)),
                ('daily_request_limit', models.IntegerField(default=100, help_text='Maximum requests per day (0 = unlimited)')),
                ('daily_token_limit', models.IntegerField(default=100000, help_text='Maximum tokens per day (0 = unlimited)')),
                ('estimated_cost_usd', models.DecimalField(decimal_places=4, default=0, help_text='Estimated total cost in USD', max_digits=10)),
                ('enabled_features', models.JSONField(blank=True, default=list, help_text='List of enabled features (improve_clarity, summarize, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.OneToOneField(help_text='Base integration connection', on_delete=django.db.models.deletion.CASCADE, related_name='llm_connection', to='integrations_app.integrationconnection')),
            ],
            options={
                'verbose_name': 'LLM Connection',
                'verbose_name_plural': 'LLM Connections',
            },
        ),
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text='Which SciTeX app used the LLM (writer, scholar, etc.)', max_length=50)),
                ('feature', models.CharField(help_text='Feature name (improve_clarity, summarize, etc.)', max_length=100)),
                ('model_used', models.CharField(help_text='Specific model used for this request', max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(default=0, help_text='Response time in milliseconds')),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Estimated cost in USD', max_digits=8)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('connection', models.ForeignKey(help_text='Which LLM connection was used', on_delete=django.db.models.deletion.CASCADE, related_name='llm_usage_logs', to='integrations_app.integrationconnection')),
            ],
            options={
                'verbose_name': 'LLM Usage Log',
                'verbose_name_plural': 'LLM Usage Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['connection', '-created_at'], name='llm_app_llm_connect_7c6661_idx'), models.Index(fields=['app_name', 'feature'], name='llm_app_llm_app_nam_95774a_idx')],
            },
        ),
    ]
