# Generated by Django 5.2.17 on 2026-09-17 22:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_app", "0005_add_share_token_to_chatsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FundedChatDailySpend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("scope", models.CharField(max_length=80)),
                (
                    "reserved_subsidy_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "provider_cost_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "subsidy_cost_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "scope"), name="uniq_funded_chat_spend_day_scope"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FundedChatDailyQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("claimed_count", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funded_chat_daily_quotas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "day"), name="uniq_funded_chat_quota_user_day"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("claimed_count__lte", 10)),
                        name="funded_chat_claimed_lte_ten",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FundedChatRateBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("request_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funded_chat_rate_buckets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "window_start"),
                        name="uniq_funded_chat_rate_user_window",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FundedChatRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("idempotency_key_hash", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                ("provider", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="reserved",
                        max_length=16,
                    ),
                ),
                (
                    "reserved_subsidy_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("provider_prompt_tokens", models.PositiveIntegerField(default=0)),
                ("provider_completion_tokens", models.PositiveIntegerField(default=0)),
                (
                    "provider_cost_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "subsidy_cost_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("response_text", models.TextField(blank=True, default="")),
                (
                    "error_category",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "retry_after_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "support_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funded_chat_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["day", "provider", "status"],
                        name="llm_app_fun_day_f20c09_idx",
                    ),
                    models.Index(
                        fields=["user", "day", "status"],
                        name="llm_app_fun_user_id_f4cd0b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "idempotency_key_hash"),
                        name="uniq_funded_chat_user_idempotency",
                    )
                ],
            },
        ),
    ]
