# Generated by Django 5.2.17 on 2026-09-17 23:48

import uuid

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.infra.llm_app.models


def populate_durable_dispatch_state(apps, schema_editor):
    Request = apps.get_model("llm_app", "FundedChatRequest")
    now = django.utils.timezone.now()
    for request in Request.objects.all().iterator():
        request.dispatch_key = uuid.uuid4().hex
        request.lease_expires_at = now
        if request.status == "reserved":
            # The old schema cannot prove whether a provider was reached.
            request.status = "reconcile_required"
            request.phase = "dispatched"
            request.reconciliation_required_at = now
        elif request.status == "succeeded":
            request.phase = "response_received"
            request.provider_responded_at = request.updated_at
        request.save(
            update_fields=[
                "dispatch_key",
                "lease_expires_at",
                "status",
                "phase",
                "reconciliation_required_at",
                "provider_responded_at",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("llm_app", "0006_fundedchatdailyspend_fundedchatdailyquota_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fundedchatrequest",
            name="dispatch_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="fundedchatrequest",
            name="dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundedchatrequest",
            name="lease_expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="fundedchatrequest",
            name="phase",
            field=models.CharField(
                choices=[
                    ("pre_dispatch", "Pre-dispatch"),
                    ("dispatched", "Provider dispatched"),
                    ("response_received", "Provider response received"),
                    ("reconciled", "Reconciled"),
                ],
                default="pre_dispatch",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="fundedchatrequest",
            name="provider_responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundedchatrequest",
            name="reconciliation_required_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fundedchatrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("reserved", "Reserved"),
                    ("dispatching", "Dispatching"),
                    ("provider_succeeded", "Provider succeeded"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("reconcile_required", "Reconciliation required"),
                    ("reconciled", "Reconciled conservatively"),
                    ("accounting_anomaly", "Accounting anomaly"),
                ],
                default="reserved",
                max_length=24,
            ),
        ),
        migrations.RunPython(
            populate_durable_dispatch_state, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="fundedchatrequest",
            name="dispatch_key",
            field=models.CharField(
                default=apps.infra.llm_app.models.funded_dispatch_key,
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="fundedchatdailyspend",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_subsidy_usd__gte", 0)),
                name="funded_spend_reserved_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundedchatdailyspend",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider_cost_usd__gte", 0)),
                name="funded_spend_provider_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundedchatdailyspend",
            constraint=models.CheckConstraint(
                condition=models.Q(("subsidy_cost_usd__gte", 0)),
                name="funded_spend_subsidy_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundedchatrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_subsidy_usd__gte", 0)),
                name="funded_request_reserved_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundedchatrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider_cost_usd__gte", 0)),
                name="funded_request_provider_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundedchatrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("subsidy_cost_usd__gte", 0)),
                name="funded_request_subsidy_nonnegative",
            ),
        ),
    ]
