# Generated by Django 5.2.17 on 2026-09-17 23:48

import uuid
from decimal import Decimal

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError

import apps.infra.llm_app.models

GLOBAL_SCOPE = "__global__"
OPERATOR_REPAIR_STATUS = "operator_repair_required"
ZERO = Decimal("0")
MONEY_FIELDS = (
    "reserved_subsidy_usd",
    "provider_cost_usd",
    "subsidy_cost_usd",
)


def _money_snapshot(row):
    return {field: str(getattr(row, field)) for field in MONEY_FIELDS}


def _has_negative_money(row):
    return any(getattr(row, field) < ZERO for field in MONEY_FIELDS)


def populate_durable_dispatch_state(apps, schema_editor):
    """Quarantine ambiguous/corrupt legacy accounting without guessing its value."""

    Request = apps.get_model("llm_app", "FundedChatRequest")
    Spend = apps.get_model("llm_app", "FundedChatDailySpend")
    now = django.utils.timezone.now()

    collision_days = set(
        Request.objects.filter(provider=GLOBAL_SCOPE).values_list("day", flat=True)
    )
    for spend in Spend.objects.all().iterator():
        metadata = dict(spend.operator_repair_metadata or {})
        update_fields = []
        if _has_negative_money(spend):
            metadata.update(
                {
                    "reason": "legacy_negative_accounting_values",
                    "accounting_state": "unknown",
                    "legacy_values": _money_snapshot(spend),
                    "migration": "llm_app.0007",
                }
            )
            for field in MONEY_FIELDS:
                if getattr(spend, field) < ZERO:
                    setattr(spend, field, ZERO)
                    update_fields.append(field)
        if spend.scope == GLOBAL_SCOPE and spend.day in collision_days:
            # A succeeded legacy collision may already have updated this single row
            # twice. Preserve every value and require an operator to repair it.
            metadata.update(
                {
                    "reason": "legacy_global_provider_scope_collision",
                    "accounting_state": "unknown",
                    "migration": "llm_app.0007",
                }
            )
        if metadata:
            spend.requires_operator_repair = True
            spend.operator_repair_metadata = metadata
            spend.save(
                update_fields=[
                    *update_fields,
                    "requires_operator_repair",
                    "operator_repair_metadata",
                    "updated_at",
                ]
            )

    for request in Request.objects.all().iterator():
        legacy_status = request.status
        request.dispatch_key = uuid.uuid4().hex
        request.lease_expires_at = now
        metadata = {}

        if request.provider == GLOBAL_SCOPE:
            metadata = {
                "reason": "legacy_global_provider_scope_collision",
                "accounting_state": "unknown",
                "legacy_status": legacy_status,
                "legacy_values": _money_snapshot(request),
                "migration": "llm_app.0007",
            }
        elif _has_negative_money(request):
            metadata = {
                "reason": "legacy_negative_accounting_values",
                "accounting_state": "unknown",
                "legacy_status": legacy_status,
                "legacy_values": _money_snapshot(request),
                "migration": "llm_app.0007",
            }

        if metadata:
            request.status = OPERATOR_REPAIR_STATUS
            request.phase = "dispatched"
            request.reconciliation_required_at = now
            request.operator_repair_metadata = metadata
            for field in MONEY_FIELDS:
                if getattr(request, field) < ZERO:
                    setattr(request, field, ZERO)
        elif legacy_status == "reserved":
            # The old schema cannot prove whether a provider was reached.
            request.status = "reconcile_required"
            request.phase = "dispatched"
            request.reconciliation_required_at = now
        elif legacy_status == "succeeded":
            request.phase = "response_received"
            request.provider_responded_at = request.updated_at
        request.save(
            update_fields=[
                "dispatch_key",
                "lease_expires_at",
                "status",
                "phase",
                "reconciliation_required_at",
                "provider_responded_at",
                "operator_repair_metadata",
                *MONEY_FIELDS,
            ]
        )


def refuse_populated_reverse(apps, schema_editor):
    """Permit schema rollback only when no funded accounting history can be lost."""

    Request = apps.get_model("llm_app", "FundedChatRequest")
    Spend = apps.get_model("llm_app", "FundedChatDailySpend")
    if Request.objects.exists() or Spend.objects.exists():
        raise IrreversibleError(
            "llm_app.0007 cannot be reversed with funded accounting rows present"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("llm_app", "0006_fundedchatdailyspend_fundedchatdailyquota_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fundedchatrequest",
            name="dispatch_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="fundedchatrequest",
            name="dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundedchatrequest",
            name="lease_expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="fundedchatrequest",
            name="operator_repair_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="fundedchatrequest",
            name="phase",
            field=models.CharField(
                choices=[
                    ("pre_dispatch", "Pre-dispatch"),
                    ("dispatched", "Provider dispatched"),
                    ("response_received", "Provider response received"),
                    ("reconciled", "Reconciled"),
                ],
                default="pre_dispatch",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="fundedchatrequest",
            name="provider_responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundedchatrequest",
            name="reconciliation_required_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundedchatdailyspend",
            name="operator_repair_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="fundedchatdailyspend",
            name="requires_operator_repair",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fundedchatrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("reserved", "Reserved"),
                    ("dispatching", "Dispatching"),
                    ("provider_succeeded", "Provider succeeded"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("reconcile_required", "Reconciliation required"),
                    ("reconciled", "Reconciled conservatively"),
                    ("accounting_anomaly", "Accounting anomaly"),
                    ("operator_repair_required", "Operator repair required"),
                ],
                default="reserved",
                max_length=24,
            ),
        ),
        # Reverse is safe only on empty ledgers; populated rollback would erase the
        # operator-repair audit trail and is rejected by the reverse callable.
        migrations.RunPython(populate_durable_dispatch_state, refuse_populated_reverse),
        migrations.AlterField(
            model_name="fundedchatrequest",
            name="dispatch_key",
            field=models.CharField(
                default=apps.infra.llm_app.models.funded_dispatch_key,
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="fundedchatdailyspend",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_subsidy_usd__gte", 0)),
                name="funded_spend_reserved_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundedchatdailyspend",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider_cost_usd__gte", 0)),
                name="funded_spend_provider_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundedchatdailyspend",
            constraint=models.CheckConstraint(
                condition=models.Q(("subsidy_cost_usd__gte", 0)),
                name="funded_spend_subsidy_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundedchatrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_subsidy_usd__gte", 0)),
                name="funded_request_reserved_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundedchatrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider_cost_usd__gte", 0)),
                name="funded_request_provider_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundedchatrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("subsidy_cost_usd__gte", 0)),
                name="funded_request_subsidy_nonnegative",
            ),
        ),
    ]
