# Generated by Django 5.2.12 on 2026-03-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_app", "0010_add_auto_response_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="apptainer_container_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Absolute path to a custom Apptainer .sif or sandbox directory. "
                    "Leave blank to use the shared default container."
                ),
                max_length=500,
            ),
        ),
    ]
