#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File: /home/ywatanabe/proj/scitex-cloud/apps/scholar_app/views/search/api_search.py
# Auto-generated by refactoring script
# ----------------------------------------
from __future__ import annotations
import os

__FILE__ = "./apps/scholar_app/views/search/api_search.py"
__DIR__ = os.path.dirname(__FILE__)
# ----------------------------------------
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.core.files.storage import default_storage
from django.core.cache import cache
from django.db.models import Q, Count, Avg, Max, Min
from django.utils import timezone
import json
import requests
import hashlib
from scitex import logging
import asyncio
from datetime import datetime, timedelta
from ...models import (
    SearchIndex, UserLibrary, Author, Journal,
    Collection, Topic, Annotation, AnnotationVote,
    CollaborationGroup, GroupMembership,
    AnnotationTag, UserPreference,
)
from apps.project_app.services import get_current_project

# Import from other search modules
from .engines import (
    search_arxiv, search_pubmed, search_semantic_scholar,
    search_pubmed_central, search_doaj, search_biorxiv, search_plos
)

logger = logging.getLogger(__name__)

# Import scitex.scholar if available
try:
    from scitex.scholar.pipelines.ScholarPipelineSearchParallel import ScholarPipelineSearchParallel
    SCITEX_SCHOLAR_AVAILABLE = True
except ImportError:
    SCITEX_SCHOLAR_AVAILABLE = False


@require_http_methods(["GET"])
def api_search_arxiv(request):
    """API endpoint for arXiv search only."""
    query = request.GET.get("q", "").strip()
    max_results = min(int(request.GET.get("max_results", 50)), 100)

    if not query:
        return JsonResponse({"error": "Query parameter required"}, status=400)

    try:
        results = search_arxiv(query, max_results=max_results)
        return JsonResponse(
            {
                "status": "success",
                "source": "arxiv",
                "query": query,
                "count": len(results),
                "results": results,
            }
        )
    except Exception as e:
        logger.error(f"arXiv API search failed: {e}")
        return JsonResponse(
            {"status": "error", "source": "arxiv", "error": str(e)}, status=500
        )


@require_http_methods(["GET"])
def api_search_pubmed(request):
    """API endpoint for PubMed search only."""
    query = request.GET.get("q", "").strip()
    max_results = min(int(request.GET.get("max_results", 50)), 100)

    if not query:
        return JsonResponse({"error": "Query parameter required"}, status=400)

    try:
        results = search_pubmed(query, max_results=max_results)
        return JsonResponse(
            {
                "status": "success",
                "source": "pubmed",
                "query": query,
                "count": len(results),
                "results": results,
            }
        )
    except Exception as e:
        logger.error(f"PubMed API search failed: {e}")
        return JsonResponse(
            {"status": "error", "source": "pubmed", "error": str(e)}, status=500
        )


@require_http_methods(["GET"])
def api_search_semantic(request):
    """API endpoint for Semantic Scholar search only."""
    query = request.GET.get("q", "").strip()
    max_results = min(int(request.GET.get("max_results", 10)), 20)

    if not query:
        return JsonResponse({"error": "Query parameter required"}, status=400)

    try:
        results = search_semantic_scholar(query, max_results=max_results)
        return JsonResponse(
            {
                "status": "success",
                "source": "semantic_scholar",
                "query": query,
                "count": len(results),
                "results": results,
            }
        )
    except Exception as e:
        logger.error(f"Semantic Scholar API search failed: {e}")
        return JsonResponse(
            {"status": "error", "source": "semantic_scholar", "error": str(e)},
            status=500,
        )


@require_http_methods(["GET"])
def api_search_pmc(request):
    """API endpoint for PMC search only."""
    query = request.GET.get("q", "").strip()
    max_results = min(int(request.GET.get("max_results", 50)), 100)

    if not query:
        return JsonResponse({"error": "Query parameter required"}, status=400)

    try:
        results = search_pubmed_central(query, max_results=max_results)
        return JsonResponse(
            {
                "status": "success",
                "source": "pmc",
                "query": query,
                "count": len(results),
                "results": results,
            }
        )
    except Exception as e:
        logger.error(f"PMC API search failed: {e}")
        return JsonResponse(
            {"status": "error", "source": "pmc", "error": str(e)}, status=500
        )


@require_http_methods(["GET"])
def api_search_doaj(request):
    """API endpoint for DOAJ search only."""
    query = request.GET.get("q", "").strip()
    max_results = min(int(request.GET.get("max_results", 25)), 50)

    if not query:
        return JsonResponse({"error": "Query parameter required"}, status=400)

    try:
        results = search_doaj(query, max_results=max_results)
        return JsonResponse(
            {
                "status": "success",
                "source": "doaj",
                "query": query,
                "count": len(results),
                "results": results,
            }
        )
    except Exception as e:
        logger.error(f"DOAJ API search failed: {e}")
        return JsonResponse(
            {"status": "error", "source": "doaj", "error": str(e)}, status=500
        )


@require_http_methods(["GET"])
def api_search_biorxiv(request):
    """API endpoint for bioRxiv search only."""
    query = request.GET.get("q", "").strip()
    max_results = min(int(request.GET.get("max_results", 25)), 50)

    if not query:
        return JsonResponse({"error": "Query parameter required"}, status=400)

    try:
        results = search_biorxiv(query, max_results=max_results)
        return JsonResponse(
            {
                "status": "success",
                "source": "biorxiv",
                "query": query,
                "count": len(results),
                "results": results,
            }
        )
    except Exception as e:
        logger.error(f"bioRxiv API search failed: {e}")
        return JsonResponse(
            {"status": "error", "source": "biorxiv", "error": str(e)}, status=500
        )


@require_http_methods(["GET"])
def api_search_plos(request):
    """API endpoint for PLOS search only."""
    query = request.GET.get("q", "").strip()
    max_results = min(int(request.GET.get("max_results", 25)), 50)

    if not query:
        return JsonResponse({"error": "Query parameter required"}, status=400)

    try:
        results = search_plos(query, max_results=max_results)
        return JsonResponse(
            {
                "status": "success",
                "source": "plos",
                "query": query,
                "count": len(results),
                "results": results,
            }
        )
    except Exception as e:
        logger.error(f"PLOS API search failed: {e}")
        return JsonResponse(
            {"status": "error", "source": "plos", "error": str(e)}, status=500
        )


@require_http_methods(["GET"])
def api_search_crossref(request):
    """API endpoint for CrossRef remote API search."""
    query = request.GET.get("q", "").strip()
    max_results = min(int(request.GET.get("max_results", 50)), 100)

    if not query:
        return JsonResponse({"error": "Query parameter required"}, status=400)

    try:
        # CrossRef API: https://api.crossref.org/works
        url = "https://api.crossref.org/works"
        params = {
            "query": query,
            "rows": max_results,
            "select": "DOI,title,author,published-print,published-online,container-title,is-referenced-by-count,abstract,URL",
        }
        headers = {
            "User-Agent": "SciTeX/1.0 (https://scitex.ai; mailto:contact@scitex.ai)"
        }

        response = requests.get(url, params=params, headers=headers, timeout=30)
        response.raise_for_status()
        data = response.json()

        results = []
        for item in data.get("message", {}).get("items", []):
            # Extract year from published date
            year = None
            for date_field in ["published-print", "published-online"]:
                if item.get(date_field, {}).get("date-parts"):
                    date_parts = item[date_field]["date-parts"][0]
                    if date_parts:
                        year = date_parts[0]
                        break

            # Format authors
            authors = []
            for author in item.get("author", []):
                name = f"{author.get('given', '')} {author.get('family', '')}".strip()
                if name:
                    authors.append(name)

            # Extract title safely (CrossRef returns title as list)
            title_list = item.get("title") or []
            title = title_list[0] if title_list else ""

            # Extract journal safely
            journal_list = item.get("container-title") or []
            journal = journal_list[0] if journal_list else ""

            results.append({
                "title": title,
                "authors": ", ".join(authors),
                "year": year,
                "journal": journal,
                "doi": item.get("DOI") or "",
                "citations": item.get("is-referenced-by-count", 0),
                "abstract": item.get("abstract") or "",
                "externalUrl": item.get("URL") or "",
                "source": "crossref",
            })

        return JsonResponse(
            {
                "status": "success",
                "source": "crossref",
                "query": query,
                "count": len(results),
                "results": results,
            }
        )
    except Exception as e:
        logger.error(f"CrossRef API search failed: {e}")
        return JsonResponse(
            {"status": "error", "source": "crossref", "error": str(e)}, status=500
        )


@require_http_methods(["GET"])
def api_search_crossref_local(request):
    """API endpoint for CrossRef Local (NAS SQLite database) search."""
    query = request.GET.get("q", "").strip()
    max_results = min(int(request.GET.get("max_results", 100)), 1000)

    if not query:
        return JsonResponse({"error": "Query parameter required"}, status=400)

    try:
        from django.conf import settings
        import os

        # Check if CrossRef Local is available
        crossref_url = getattr(settings, 'CROSSREF_INTERNAL_URL', None)
        if not crossref_url:
            crossref_url = os.environ.get('CROSSREF_INTERNAL_URL')

        if not crossref_url:
            # Service not configured - return gracefully
            return JsonResponse(
                {
                    "status": "success",
                    "source": "crossref_local",
                    "query": query,
                    "count": 0,
                    "results": [],
                    "note": "CrossRef Local database not available in this environment",
                }
            )

        # Proxy to internal CrossRef service
        url = f"{crossref_url}/api/search/"
        params = {"title": query, "limit": max_results}

        response = requests.get(url, params=params, timeout=10)
        response.raise_for_status()
        data = response.json()

        # Convert to standard format
        results = []
        for item in data.get("results", []):
            title = item.get("title") or ""
            doi = item.get("doi") or ""
            results.append({
                "title": title,
                "authors": item.get("authors") or "",
                "year": item.get("year"),
                "journal": item.get("journal") or "",
                "doi": doi,
                "citations": item.get("citation_count", 0),
                "abstract": "",
                "externalUrl": f"https://doi.org/{doi}" if doi else "",
                "source": "crossref_local",
            })

        return JsonResponse(
            {
                "status": "success",
                "source": "crossref_local",
                "query": query,
                "count": len(results),
                "results": results,
            }
        )
    except requests.exceptions.ConnectionError:
        # Service not running - return gracefully
        logger.warning("CrossRef Local service not available")
        return JsonResponse(
            {
                "status": "success",
                "source": "crossref_local",
                "query": query,
                "count": 0,
                "results": [],
                "note": "CrossRef Local service not running",
            }
        )
    except Exception as e:
        logger.error(f"CrossRef Local search failed: {e}")
        return JsonResponse(
            {"status": "error", "source": "crossref_local", "error": str(e)}, status=500
        )


@require_http_methods(["GET"])
def api_search_openalex(request):
    """API endpoint for OpenAlex search."""
    query = request.GET.get("q", "").strip()
    max_results = min(int(request.GET.get("max_results", 50)), 100)

    if not query:
        return JsonResponse({"error": "Query parameter required"}, status=400)

    try:
        # OpenAlex API: https://api.openalex.org/works
        url = "https://api.openalex.org/works"
        params = {
            "search": query,
            "per-page": max_results,
            "select": "id,doi,title,authorships,publication_year,primary_location,cited_by_count,abstract_inverted_index,open_access",
        }
        headers = {
            "User-Agent": "SciTeX/1.0 (https://scitex.ai; mailto:contact@scitex.ai)"
        }

        response = requests.get(url, params=params, headers=headers, timeout=30)
        response.raise_for_status()
        data = response.json()

        results = []
        for item in data.get("results", []):
            # Format authors
            authors = []
            for authorship in item.get("authorships", []):
                author = authorship.get("author", {})
                name = author.get("display_name", "")
                if name:
                    authors.append(name)

            # Reconstruct abstract from inverted index
            abstract = ""
            abstract_idx = item.get("abstract_inverted_index")
            if abstract_idx:
                try:
                    words = [""] * (max(max(positions) for positions in abstract_idx.values()) + 1)
                    for word, positions in abstract_idx.items():
                        for pos in positions:
                            words[pos] = word
                    abstract = " ".join(words)
                except (ValueError, TypeError):
                    abstract = ""

            # Get journal from primary location
            journal = ""
            primary_loc = item.get("primary_location") or {}
            if primary_loc and primary_loc.get("source"):
                journal = primary_loc["source"].get("display_name", "") or ""

            # Clean DOI
            doi = item.get("doi") or ""
            if doi.startswith("https://doi.org/"):
                doi = doi.replace("https://doi.org/", "")

            # Handle title - ensure it's never None
            title = item.get("title") or ""

            results.append({
                "title": title,
                "authors": ", ".join(authors[:5]) + ("..." if len(authors) > 5 else ""),
                "year": item.get("publication_year"),
                "journal": journal,
                "doi": doi,
                "citations": item.get("cited_by_count", 0),
                "abstract": abstract[:500] + "..." if len(abstract) > 500 else abstract,
                "is_open_access": item.get("open_access", {}).get("is_oa", False),
                "externalUrl": f"https://doi.org/{doi}" if doi else "",
                "source": "openalex",
            })

        return JsonResponse(
            {
                "status": "success",
                "source": "openalex",
                "query": query,
                "count": len(results),
                "results": results,
            }
        )
    except Exception as e:
        logger.error(f"OpenAlex API search failed: {e}")
        return JsonResponse(
            {"status": "error", "source": "openalex", "error": str(e)}, status=500
        )


# =============================================================================
# Unified RESTful Search API with Command Syntax Support
# =============================================================================

from concurrent.futures import ThreadPoolExecutor, as_completed
from .search_helpers import parse_query_operators, apply_advanced_filters
from ...middleware.rate_limit import rate_limit, rate_limit_status
from ...api_auth import api_key_optional


@api_key_optional
@rate_limit("api_search_unified")
@require_http_methods(["GET"])
def api_search_unified(request):
    """
    Unified RESTful API for academic literature search.

    Supports shell-style command syntax for filtering:
    - `-t VALUE` or `--title VALUE`: Title filter (include)
    - `-t -VALUE`: Title filter (exclude)
    - `-a VALUE` or `--author VALUE`: Author filter
    - `-j VALUE` or `--journal VALUE`: Journal filter
    - `-ymin YYYY` or `--year-min`: Minimum year
    - `-ymax YYYY` or `--year-max`: Maximum year
    - `-cmin N` or `--citations-min`: Minimum citations
    - `-cmax N` or `--citations-max`: Maximum citations
    - `-ifmin N` or `--if-min`: Minimum impact factor
    - `-ifmax N` or `--if-max`: Maximum impact factor

    Query Parameters:
    - q (required): Search query with optional command syntax
    - sources: Comma-separated list of sources (default: all available)
               Options: pubmed,arxiv,semantic,crossref,openalex,pmc,doaj,biorxiv,plos
    - max_results: Maximum results per source (default: 20, max: 100)
    - format: Response format - 'full' or 'compact' (default: full)

    Example:
        GET /scholar/api/search/?q=neural network -t deep learning -a Smith -ymin 2020 -cmin 50
        GET /scholar/api/search/?q=CRISPR&sources=pubmed,arxiv&max_results=50

    Returns:
        JSON response with aggregated search results from all sources.
    """
    query = request.GET.get("q", "").strip()
    if not query:
        return JsonResponse({
            "status": "error",
            "error": "Query parameter 'q' is required",
            "syntax_help": {
                "title_filter": "-t VALUE (include) or -t -VALUE (exclude)",
                "author_filter": "-a VALUE or --author VALUE",
                "journal_filter": "-j VALUE or --journal VALUE",
                "year_range": "-ymin YYYY -ymax YYYY",
                "citations_min": "-cmin N",
                "impact_factor_min": "-ifmin N",
                "example": "neural network -t deep learning -a Smith -ymin 2020"
            }
        }, status=400)

    # Parse command syntax from query
    parsed = parse_query_operators(query)
    clean_query = parsed.get("query", query)

    # Get sources to search
    sources_param = request.GET.get("sources", "").strip()
    available_sources = {
        "pubmed": search_pubmed,
        "arxiv": search_arxiv,
        "semantic": search_semantic_scholar,
        "pmc": search_pubmed_central,
        "doaj": search_doaj,
        "biorxiv": search_biorxiv,
        "plos": search_plos,
    }

    if sources_param:
        requested_sources = [s.strip().lower() for s in sources_param.split(",")]
        sources_to_search = {k: v for k, v in available_sources.items() if k in requested_sources}
    else:
        # Default to main sources for performance
        sources_to_search = {
            "pubmed": search_pubmed,
            "arxiv": search_arxiv,
            "semantic": search_semantic_scholar,
        }

    # Get max results per source
    try:
        max_results = min(int(request.GET.get("max_results", 20)), 100)
    except ValueError:
        max_results = 20

    # Response format
    response_format = request.GET.get("format", "full").lower()

    # Search all sources in parallel
    all_results = []
    source_stats = {}
    errors = []

    def search_source(name, search_func):
        try:
            results = search_func(clean_query, max_results=max_results)
            return name, results, None
        except Exception as e:
            return name, [], str(e)

    with ThreadPoolExecutor(max_workers=len(sources_to_search)) as executor:
        futures = {
            executor.submit(search_source, name, func): name
            for name, func in sources_to_search.items()
        }

        for future in as_completed(futures):
            source_name, results, error = future.result()
            if error:
                errors.append({"source": source_name, "error": error})
                source_stats[source_name] = {"count": 0, "status": "error"}
            else:
                source_stats[source_name] = {"count": len(results), "status": "success"}
                all_results.extend(results)

    # Apply filters from parsed operators
    filtered_results = apply_advanced_filters(all_results, None, parsed)

    # Sort by citations (descending), then by year (descending)
    filtered_results.sort(
        key=lambda x: (
            -(x.get("citations") or 0),
            -(int(x.get("year") or 0))
        )
    )

    # Format response
    if response_format == "compact":
        # Compact format - only essential fields
        formatted_results = [
            {
                "title": r.get("title"),
                "authors": r.get("authors"),
                "year": r.get("year"),
                "journal": r.get("journal"),
                "doi": r.get("doi"),
                "citations": r.get("citations"),
                "source": r.get("source"),
            }
            for r in filtered_results
        ]
    else:
        formatted_results = filtered_results

    return JsonResponse({
        "status": "success",
        "query": {
            "original": query,
            "parsed": clean_query,
            "filters": {
                "title_includes": parsed.get("title_includes", []),
                "title_excludes": parsed.get("title_excludes", []),
                "author_includes": parsed.get("author_includes", []),
                "author_excludes": parsed.get("author_excludes", []),
                "journal_includes": parsed.get("journal_includes", []),
                "journal_excludes": parsed.get("journal_excludes", []),
                "year_min": parsed.get("year_min"),
                "year_max": parsed.get("year_max"),
                "citations_min": parsed.get("citations_min"),
                "citations_max": parsed.get("citations_max"),
                "impact_factor_min": parsed.get("impact_factor_min"),
                "impact_factor_max": parsed.get("impact_factor_max"),
            }
        },
        "sources": source_stats,
        "total_count": len(filtered_results),
        "results": formatted_results,
        "errors": errors if errors else None,
        "rate_limit": rate_limit_status(request, "api_search_unified"),
    })


@require_http_methods(["GET"])
def api_search_syntax_help(request):
    """
    API endpoint to get search syntax documentation.

    Returns detailed documentation on available search operators and examples.
    """
    return JsonResponse({
        "status": "success",
        "syntax": {
            "title_filter": {
                "short": "-t",
                "long": "--title",
                "description": "Filter by title content",
                "include_example": "-t neural",
                "exclude_example": "-t -mouse",
            },
            "author_filter": {
                "short": "-a",
                "long": "--author",
                "description": "Filter by author name",
                "include_example": "-a Smith",
                "exclude_example": "-a -Jones",
            },
            "journal_filter": {
                "short": "-j",
                "long": "--journal",
                "description": "Filter by journal name",
                "include_example": "-j Nature",
                "exclude_example": "-j -arXiv",
            },
            "year_min": {
                "short": "-ymin",
                "long": "--year-min",
                "description": "Minimum publication year",
                "example": "-ymin 2020",
            },
            "year_max": {
                "short": "-ymax",
                "long": "--year-max",
                "description": "Maximum publication year",
                "example": "-ymax 2024",
            },
            "citations_min": {
                "short": "-cmin",
                "long": "--citations-min",
                "description": "Minimum citation count",
                "example": "-cmin 100",
            },
            "citations_max": {
                "short": "-cmax",
                "long": "--citations-max",
                "description": "Maximum citation count",
                "example": "-cmax 1000",
            },
            "impact_factor_min": {
                "short": "-ifmin",
                "long": "--if-min",
                "description": "Minimum journal impact factor",
                "example": "-ifmin 5",
            },
            "impact_factor_max": {
                "short": "-ifmax",
                "long": "--if-max",
                "description": "Maximum journal impact factor",
                "example": "-ifmax 50",
            },
        },
        "examples": [
            {
                "query": "neural network -t deep learning -ymin 2020",
                "description": "Search for 'neural network', title must contain 'deep learning', published since 2020"
            },
            {
                "query": "CRISPR -a Doudna -j Nature -cmin 100",
                "description": "Search for 'CRISPR' by author Doudna in Nature journal with at least 100 citations"
            },
            {
                "query": "cancer treatment -t -mouse -t -rat -ymin 2022",
                "description": "Search for 'cancer treatment', exclude mouse and rat studies, since 2022"
            },
            {
                "query": "machine learning -ifmin 10 -cmin 50",
                "description": "Search 'machine learning' in journals with IF ≥ 10 and papers with ≥ 50 citations"
            },
        ],
        "available_sources": [
            "pubmed", "arxiv", "semantic", "crossref", "openalex",
            "pmc", "doaj", "biorxiv", "plos"
        ],
        "query_parameters": {
            "q": "Search query with optional command syntax (required)",
            "sources": "Comma-separated list of sources to search (optional)",
            "max_results": "Maximum results per source, 1-100 (default: 20)",
            "format": "'full' or 'compact' response format (default: full)",
        }
    })

