"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import shutil

import pytest


def test_audit_all_clean():
    # Arrange
    # Act
    # Assert
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    audit_all_for_package(
        "scitex-hub",
        # The audit-all umbrella re-installs the package and walks every
        # sub-auditor; on CI the cold path (pip resolve + corpus load) can
        # run well past the 120 s default, so give it generous headroom.
        timeout=600.0,
        skip_rules=(
            # --- Project-structure backlog (audit-project) ---
            # Pre-existing structural conventions deferred while the apps/
            # standardization settles. These post-date the bulk of this
            # tree and are tracked separately.
            "PS102",
            "PS105",
            "PS112",
            "PS114",
            "PS121",
            "PS122",
            "PS123",
            "PS126",
            "PS129",
            "PS133",
            "PS202",
            "PS203",
            "PS204",
            # PA-202 (version-not-from-metadata) and PA-501
            # (missing-future-annotations) are warn-level Python-API backlog
            # on the package root `__init__.py`; deferred with the rest of the
            # PA migration. Hyphenated to match the auditor's `[PA-202 …]` tag.
            "PA-202",
            "PA-501",
            # --- Test-hygiene backlog (audit-python-apis) ---
            # The no-mocks (PA-306) and test-quality (PA-307) rules ship at
            # error severity but post-date this suite. The project is marked
            # `deferred` in `.scitex/dev/config.yaml`, which suppresses them
            # locally — but the per-package auditors resolve their config
            # repo-root from the ECOSYSTEM registry's dev-box `local_path`,
            # absent on CI runners, so the deferral cannot apply there. Masked
            # here the same way scitex-io / scitex-orochi do; the tests
            # themselves still run and pass. Tracked under the ecosystem
            # TQ-migration (de-mocking + AAA-splitting).
            "PA-306",
            "PA-307",
            # --- CLI / MCP convention backlog (audit-cli, audit-mcp-tools) ---
            # The §-rules cover the noun-verb CLI shape, the command
            # dictionary, read-/mutating-verb flags (--json / --dry-run /
            # --yes), help examples, required skills tools, and Python-API
            # <-> MCP-tool parity. The CLI predates these rules; the noun-verb
            # migration is a large, separate campaign. Masked so the gate
            # stays green while the CLI migration lands incrementally — the
            # CLI itself works and is exercised by tests/scitex_hub/test_cli.py.
            "§1",
            "§1a",
            "§1d",
            "§2",
            "§4",
            "§5",
            "§6",
            "§6b",
            "§10",
            # The `deferred` project-type emits an informational
            # `[defer] … PS-103 finding(s) suppressed` notice on stdout. It is
            # not a violation, but the gate's line-scanner treats any
            # unmatched `[`-prefixed line as blocking, so acknowledge it here.
            "defer",
        ),
    )
