# Generated by Django 5.2.10 on 2026-02-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0009_add_gpu_percent_to_servermetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField(help_text='Comma-separated author names')),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('page', models.CharField(blank=True, max_length=50)),
                ('abstract', models.TextField(blank=True)),
                ('paper_url', models.URLField(blank=True, null=True)),
                ('code_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('preprint', 'Preprint'), ('in_preparation', 'In Preparation')], default='published', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['display_order', '-year', 'title'],
            },
        ),
    ]
