# Generated by Django 6.0.6 on 2026-07-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0011_billingevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHealthProbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('response_time_ms', models.FloatField(help_text='Response time in milliseconds (null when probe failed)', null=True)),
                ('is_healthy', models.BooleanField(help_text='HTTP 200 within timeout')),
                ('status_code', models.IntegerField(help_text='HTTP status code (null when no response)', null=True)),
            ],
            options={
                'verbose_name': 'Site Health Probe',
                'verbose_name_plural': 'Site Health Probes',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='public_app__timesta_a23cfa_idx')],
            },
        ),
    ]
