# Generated by Django 6.0.6 on 2026-07-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0011_billingevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='お名前')),
                ('affiliation', models.CharField(blank=True, max_length=200, verbose_name='ご所属')),
                ('request', models.TextField(verbose_name='ご相談内容')),
                ('budget', models.CharField(blank=True, max_length=120, verbose_name='ご予算感')),
                ('handled', models.BooleanField(default=False, verbose_name='対応済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Inquiry',
                'verbose_name_plural': 'Service Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
