# Generated by Django 6.0.8 on 2026-09-17 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0016_remove_servermetrics_visitor_pool_allocated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingevent',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingevent',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='billingevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingevent',
            name='status',
            field=models.CharField(choices=[('received', 'Received, not yet processed'), ('processing', 'Claimed by a worker'), ('processed', 'Applied to local state'), ('failed', 'Last attempt raised; a retry may claim it')], default='received', max_length=16),
        ),
        migrations.AddField(
            model_name='billingevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BillingSetupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe', max_length=32)),
                ('pricing_id', models.CharField(blank=True, default='', max_length=64)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('session_url', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='open', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_setup', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Setup Session',
                'verbose_name_plural': 'Billing Setup Sessions',
            },
        ),
    ]
