#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Signup asks for the password once — no confirmation field.

Card: hub-signup-email-stripe-funnel-20260917 — "Remove confirm-password field;
untouched password requirements neutral, validate after interaction; server/client
policy identical".

Measured before this change: `password2` existed as a required CharField in BOTH
signup forms (auth_app/forms.py:35 and public_app/forms.py:130), each with a
`clean()` that raised "Passwords do not match.", and signup.html rendered the
field with five separate JS references to `#id_password2` — a match check on
submit, an input listener, a toggle button and two lookups. The client already
advertised "password requirements: ..." rules, so the field was pure friction
with two places to keep in step.

Email verification and password reset are the recovery path (SSOT §2), which is
what makes the confirmation field redundant rather than a safety net.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[3]
SIGNUP_TEMPLATE = REPO / "apps/infra/auth_app/templates/auth_app/signup.html"

VALID = {
    "username": "researcher01",
    "email": "researcher01@example.com",
    "password": "ValidPassword123!",  # pragma: allowlist secret
    "agree_terms": True,
}


def _signup_forms():
    from apps.infra.auth_app.forms import SignupForm as AuthSignupForm

    forms = [AuthSignupForm]
    try:
        from apps.infra.public_app.forms import SignupForm as PublicSignupForm

        forms.append(PublicSignupForm)
    except ImportError:  # pragma: no cover — the public copy is the same form
        pass
    return forms


def test_neither_signup_form_defines_a_confirmation_field():
    for form in _signup_forms():
        assert "password2" not in form.base_fields, (
            f"{form.__module__}.{form.__name__} still requires a confirmation field"
        )


def test_no_form_still_validates_that_two_passwords_match():
    for form in _signup_forms():
        source = Path(form.__module__.replace(".", "/") + ".py")
        text = (REPO / source).read_text() if (REPO / source).is_file() else ""
        if text:
            assert "Passwords do not match" not in text, (
                f"{form.__module__} still compares two password inputs"
            )


def test_the_template_renders_one_password_field():
    html = SIGNUP_TEMPLATE.read_text()

    assert "password2" not in html, "the signup template still renders a confirmation field"
    assert "Confirm Password" not in html, "the confirmation label is still shown"
    # The id is generated by Django from the field name, so it is the JS that
    # must be checked for stale references — not the source for a literal id.
    assert 'getElementById("id_password2")' not in html, "dead JS still reaches for #id_password2"
    assert "{{ form.password }}" in html, "the password field itself disappeared"
    assert 'getElementById("id_password")' in html


def test_the_password_requirements_stay_visible():
    """"untouched password requirements neutral" — the rules remain, as rules."""
    html = SIGNUP_TEMPLATE.read_text()

    assert "Password Requirements" in html
    assert re.search(r'class="password-rules', html)


def test_the_fields_carry_correct_autocomplete_hints():
    """Card: "correct autocomplete/accessibility".

    Measured before this change: the signup widgets carried no autocomplete
    attribute at all, so password managers could not fill or offer to save, and
    the six-digit emailed code asked for autocomplete="off" — which switches off
    exactly the autofill that exists for it.
    """
    for form in _signup_forms():
        fields = form.base_fields
        attrs = {name: fields[name].widget.attrs.get("autocomplete")
                 for name in ("username", "email", "password")}
        assert attrs == {"username": "username", "email": "email",
                         "password": "new-password"}, (
            f"{form.__name__} has wrong autocomplete hints: {attrs}"
        )


def test_the_email_code_field_asks_for_one_time_code():
    from apps.infra.public_app.forms import VerifyCodeForm

    widget_attrs = VerifyCodeForm.base_fields["code"].widget.attrs
    assert widget_attrs.get("autocomplete") == "one-time-code", (
        "the six-digit email code must not switch autofill off"
    )


# ---------------------------------------------------------------------------
# server behaviour (database gate, runs in CI)
# ---------------------------------------------------------------------------


@pytest.mark.django_db
def test_a_signup_without_a_confirmation_field_is_valid():
    """The server must not demand what the form no longer shows."""
    for form in _signup_forms():
        form_instance = form(data=dict(VALID))
        assert form_instance.is_valid(), (
            f"{form.__name__} rejected a signup that has no password2: "
            f"{form_instance.errors.as_json()}"
        )


@pytest.mark.django_db
def test_a_legacy_confirmation_key_is_ignored_not_required():
    """Older clients and the e2e suite still post password2; it must be inert."""
    for form in _signup_forms():
        payload = dict(VALID, password2="something-else-entirely")
        form_instance = form(data=payload)
        assert form_instance.is_valid(), (
            f"{form.__name__} still reacts to password2: {form_instance.errors.as_json()}"
        )


# EOF
