# Generated by Django 5.2.11 on 2026-02-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_app", "0004_alter_marketplacemodule_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplacemodule",
            name="pinned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketplacemodule",
            name="pinned_commit",
            field=models.CharField(
                blank=True,
                help_text="SHA of the approved commit (set on approval)",
                max_length=40,
            ),
        ),
    ]
