# Generated by Django 5.2.12 on 2026-03-09 03:50

from django.db import migrations, models

import apps.workspace.apps_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_app", "0012_add_registry_repo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="devinstallation",
            name="apptainer_container_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Absolute path to a custom Apptainer .sif for this app. "
                    "Leave blank to use the user's default container."
                ),
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="moduleversion",
            name="version",
            field=models.CharField(
                max_length=20,
                validators=[apps.workspace.apps_app.models._validate_version],
            ),
        ),
    ]
