# Generated by Django 6.0.6 on 2026-07-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_app', '0013_devinstallation_apptainer_container_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsmodule',
            name='category',
            field=models.CharField(choices=[('writing', 'Writing'), ('visualization', 'Visualization'), ('data', 'Data'), ('analysis', 'Analysis'), ('reference', 'Reference'), ('utility', 'Utility'), ('social', 'Social'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
