# Generated by Django 5.2.11 on 2026-02-22 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HashRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(db_index=True, max_length=64)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("session", "Session"),
                            ("file", "File"),
                            ("stamp", "Stamp"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hash_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-registered_at"],
                        name="clew_app_ha_user_id_30b7d7_idx",
                    )
                ],
                "unique_together": {("hash", "user")},
            },
        ),
    ]
