# Generated by Django 5.2.7 on 2026-01-21 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_authenticateddevice_deviceaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device info')),
                ('login_method', models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google OAuth'), ('github', 'GitHub OAuth'), ('visitor', 'Visitor Account'), ('other', 'Other')], default='email', max_length=20)),
                ('success', models.BooleanField(default=True, help_text='Whether login succeeded')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason if login failed', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='auth_app_lo_user_id_0010eb_idx'), models.Index(fields=['-timestamp'], name='auth_app_lo_timesta_102c67_idx')],
            },
        ),
    ]
