#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Tests for apps/scholar_app/views/search/api_search.py"""

import pytest

# from apps.scholar_app.views.search.api_search import ...


class TestPlaceholder:
    """Placeholder test class - replace with actual tests."""

    def test_placeholder(self):
        """Placeholder test - implement actual tests."""
        pytest.skip("Not implemented yet")

if __name__ == "__main__":
    import os

    import pytest

    pytest.main([os.path.abspath(__file__)])

# --------------------------------------------------------------------------------
# Start of Source Code from: apps/scholar_app/views/search/api_search.py
# --------------------------------------------------------------------------------
# #!/usr/bin/env python3
# # -*- coding: utf-8 -*-
# # File: /home/ywatanabe/proj/scitex-cloud/apps/scholar_app/views/search/api_search.py
# # Auto-generated by refactoring script
# # ----------------------------------------
# from __future__ import annotations
# import os
# 
# __FILE__ = "./apps/scholar_app/views/search/api_search.py"
# __DIR__ = os.path.dirname(__FILE__)
# # ----------------------------------------
# from django.shortcuts import render
# from django.http import JsonResponse
# from django.views.decorators.http import require_http_methods
# from django.contrib.auth.decorators import login_required
# from django.views.decorators.csrf import csrf_exempt
# from django.core.files.storage import default_storage
# from django.core.cache import cache
# from django.db.models import Q, Count, Avg, Max, Min
# from django.utils import timezone
# import json
# import requests
# import hashlib
# from scitex import logging
# import asyncio
# from datetime import datetime, timedelta
# from ...models import (
#     SearchIndex, UserLibrary, Author, Journal,
#     Collection, Topic, Annotation, AnnotationVote,
#     CollaborationGroup, GroupMembership,
#     AnnotationTag, UserPreference,
# )
# from apps.project_app.services import get_current_project
# 
# # Import from other search modules
# from .engines import (
#     search_arxiv, search_pubmed, search_semantic_scholar,
#     search_pubmed_central, search_doaj, search_biorxiv, search_plos
# )
# from .citations import get_journal_impact_factor
# 
# logger = logging.getLogger(__name__)
# 
# 
# def cached_search(request, source_name, search_func, max_results, cache_ttl=1800):
#     """
#     Helper for cached API searches with ignore_cache support.
# 
#     Args:
#         request: Django request object
#         source_name: Name of the source (e.g., 'arxiv', 'pubmed')
#         search_func: Function to call for search (takes query and max_results)
#         max_results: Maximum results to return
#         cache_ttl: Cache time-to-live in seconds (default 30 minutes)
# 
#     Returns:
#         JsonResponse with search results or error
#     """
#     from .config import get_limit_for_source
# 
#     query = request.GET.get("q", "").strip()
#     ignore_cache = request.GET.get("ignore_cache", "").lower() == "true"
# 
#     if not query:
#         return JsonResponse({"error": "Query parameter required"}, status=400)
# 
#     # Check cache unless ignore_cache is set
#     cache_key = f"{source_name}_search_{hashlib.md5(f'{query}_{max_results}'.encode()).hexdigest()}"
#     if not ignore_cache:
#         cached = cache.get(cache_key)
#         if cached:
#             cached["cached"] = True
#             return JsonResponse(cached)
# 
#     try:
#         results = search_func(query, max_results=max_results)
#         result_count = len(results)
#         configured_max = get_limit_for_source(source_name, request.user if request.user.is_authenticated else None)
# 
#         # Build result guidance
#         result_guidance = _build_result_guidance(
#             source_name=source_name,
#             received=result_count,
#             requested=max_results,
#             configured_max=configured_max,
#         )
# 
#         response_data = {
#             "status": "success",
#             "source": source_name,
#             "query": query,
#             "count": result_count,
#             "results": results,
#             "result_guidance": result_guidance,
#         }
#         # Cache the results
#         cache.set(cache_key, response_data, cache_ttl)
#         return JsonResponse(response_data)
#     except Exception as e:
#         logger.error(f"{source_name} API search failed: {e}")
#         return JsonResponse(
#             {"status": "error", "source": source_name, "error": str(e)}, status=500
#         )
# 
# 
# def _build_result_guidance(source_name, received, requested, configured_max, error=None):
#     """
#     Build result guidance dict explaining why results are limited.
# 
#     Args:
#         source_name: Name of the search source
#         received: Number of results actually received
#         requested: Number of results requested
#         configured_max: Maximum configured for this source
#         error: Error message if any
# 
#     Returns:
#         dict with guidance information
#     """
#     # Source-specific rate limit explanations
#     rate_limit_info = {
#         "pubmed": "PubMed API: 3 requests/sec without API key",
#         "arxiv": "arXiv API: 1 request/3 sec recommended",
#         "semantic_scholar": "Semantic Scholar: 10 results max, strict rate limits",
#         "crossref": "CrossRef API: Polite pool (faster with contact email)",
#         "crossref_local": "Local database: No rate limits",
#         "openalex": "OpenAlex API: 10 requests/sec max",
#         "pmc": "PMC API: Similar to PubMed limits",
#         "doaj": "DOAJ API: Moderate rate limits",
#         "biorxiv": "bioRxiv API: Moderate rate limits",
#         "plos": "PLOS API: Moderate rate limits",
#     }
# 
#     # Build reason explanation
#     if error:
#         reason = f"Error: {error}"
#     elif received == 0:
#         reason = "No matching results found"
#     elif received < requested:
#         reasons = []
#         if source_name in rate_limit_info:
#             reasons.append(rate_limit_info[source_name])
#         if received < 5:
#             reasons.append("Very few matches - try broader terms")
#         elif received < requested // 2:
#             reasons.append("API returned fewer than requested")
#         reason = " | ".join(reasons) if reasons else f"Returned {received}/{requested}"
#     else:
#         reason = f"Received all {received} requested results"
# 
#     return {
#         "source": source_name,
#         "requested": requested,
#         "received": received,
#         "configured_max": configured_max,
#         "reason": reason,
#         "rate_limit_info": rate_limit_info.get(source_name, "Unknown"),
#     }
# 
# 
# # Import scitex.scholar if available
# try:
#     from scitex.scholar.pipelines.ScholarPipelineSearchParallel import ScholarPipelineSearchParallel
#     SCITEX_SCHOLAR_AVAILABLE = True
# except ImportError:
#     SCITEX_SCHOLAR_AVAILABLE = False
# 
# 
# @require_http_methods(["GET"])
# def api_search_arxiv(request):
#     """API endpoint for arXiv search only."""
#     max_results = min(int(request.GET.get("max_results", 50)), 100)
#     return cached_search(request, "arxiv", search_arxiv, max_results)
# 
# 
# @require_http_methods(["GET"])
# def api_search_pubmed(request):
#     """API endpoint for PubMed search only."""
#     max_results = min(int(request.GET.get("max_results", 50)), 100)
#     return cached_search(request, "pubmed", search_pubmed, max_results)
# 
# 
# @require_http_methods(["GET"])
# def api_search_semantic(request):
#     """API endpoint for Semantic Scholar search only."""
#     max_results = min(int(request.GET.get("max_results", 10)), 20)
#     return cached_search(request, "semantic_scholar", search_semantic_scholar, max_results)
# 
# 
# @require_http_methods(["GET"])
# def api_search_pmc(request):
#     """API endpoint for PMC search only."""
#     max_results = min(int(request.GET.get("max_results", 50)), 100)
#     return cached_search(request, "pmc", search_pubmed_central, max_results)
# 
# 
# @require_http_methods(["GET"])
# def api_search_doaj(request):
#     """API endpoint for DOAJ search only."""
#     max_results = min(int(request.GET.get("max_results", 25)), 50)
#     return cached_search(request, "doaj", search_doaj, max_results)
# 
# 
# @require_http_methods(["GET"])
# def api_search_biorxiv(request):
#     """API endpoint for bioRxiv search only."""
#     max_results = min(int(request.GET.get("max_results", 25)), 50)
#     return cached_search(request, "biorxiv", search_biorxiv, max_results)
# 
# 
# @require_http_methods(["GET"])
# def api_search_plos(request):
#     """API endpoint for PLOS search only."""
#     max_results = min(int(request.GET.get("max_results", 25)), 50)
#     return cached_search(request, "plos", search_plos, max_results)
# 
# 
# @require_http_methods(["GET"])
# def api_search_crossref(request):
#     """API endpoint for CrossRef remote API search."""
#     query = request.GET.get("q", "").strip()
#     max_results = min(int(request.GET.get("max_results", 50)), 100)
#     ignore_cache = request.GET.get("ignore_cache", "").lower() == "true"
# 
#     if not query:
#         return JsonResponse({"error": "Query parameter required"}, status=400)
# 
#     # Check cache
#     cache_key = f"crossref_search_{hashlib.md5(f'{query}_{max_results}'.encode()).hexdigest()}"
#     if not ignore_cache:
#         cached = cache.get(cache_key)
#         if cached:
#             cached["cached"] = True
#             return JsonResponse(cached)
# 
#     try:
#         # CrossRef API: https://api.crossref.org/works
#         url = "https://api.crossref.org/works"
#         params = {
#             "query": query,
#             "rows": max_results,
#             "select": "DOI,title,author,published-print,published-online,container-title,is-referenced-by-count,abstract,URL,license,link",
#         }
#         headers = {
#             "User-Agent": "SciTeX/1.0 (https://scitex.ai; mailto:contact@scitex.ai)"
#         }
# 
#         response = requests.get(url, params=params, headers=headers, timeout=30)
#         response.raise_for_status()
#         data = response.json()
# 
#         results = []
#         for item in data.get("message", {}).get("items", []):
#             # Extract year from published date
#             year = None
#             for date_field in ["published-print", "published-online"]:
#                 if item.get(date_field, {}).get("date-parts"):
#                     date_parts = item[date_field]["date-parts"][0]
#                     if date_parts:
#                         year = date_parts[0]
#                         break
# 
#             # Format authors
#             authors = []
#             for author in item.get("author", []):
#                 name = f"{author.get('given', '')} {author.get('family', '')}".strip()
#                 if name:
#                     authors.append(name)
# 
#             # Extract title safely (CrossRef returns title as list)
#             title_list = item.get("title") or []
#             title = title_list[0].strip() if title_list and title_list[0] else ""
# 
#             # Skip papers without titles - they are not useful for users
#             if not title:
#                 continue
# 
#             # Extract journal safely
#             journal_list = item.get("container-title") or []
#             journal = journal_list[0] if journal_list else ""
# 
#             # Detect open access from license info
#             is_open_access = False
#             pdf_url = ""
#             licenses = item.get("license") or []
#             for lic in licenses:
#                 lic_url = lic.get("URL", "").lower()
#                 # Check for Creative Commons or open licenses
#                 if any(oa in lic_url for oa in ["creativecommons.org", "cc-by", "open-access", "public-domain"]):
#                     is_open_access = True
#                     break
# 
#             # Also check for PDF links
#             links = item.get("link") or []
#             for link in links:
#                 content_type = link.get("content-type", "")
#                 if "pdf" in content_type.lower():
#                     pdf_url = link.get("URL", "")
#                     # Vor publishers often provide free PDF links
#                     if pdf_url:
#                         is_open_access = True
#                     break
# 
#             # Get impact factor for journal
#             impact_factor = get_journal_impact_factor(journal) if journal else None
# 
#             results.append({
#                 "title": title,
#                 "authors": ", ".join(authors),
#                 "year": year,
#                 "journal": journal,
#                 "doi": item.get("DOI") or "",
#                 "citations": item.get("is-referenced-by-count", 0),
#                 "abstract": item.get("abstract") or "",
#                 "externalUrl": item.get("URL") or "",
#                 "source": "crossref",
#                 "is_open_access": is_open_access,
#                 "pdf_url": pdf_url,
#                 "impact_factor": impact_factor,
#             })
# 
#         from .config import get_limit_for_source
#         result_count = len(results)
#         configured_max = get_limit_for_source("crossref", request.user if request.user.is_authenticated else None)
# 
#         response_data = {
#             "status": "success",
#             "source": "crossref",
#             "query": query,
#             "count": result_count,
#             "results": results,
#             "result_guidance": _build_result_guidance(
#                 source_name="crossref",
#                 received=result_count,
#                 requested=max_results,
#                 configured_max=configured_max,
#             ),
#         }
#         cache.set(cache_key, response_data, 1800)
#         return JsonResponse(response_data)
#     except Exception as e:
#         logger.error(f"CrossRef API search failed: {e}")
#         return JsonResponse(
#             {"status": "error", "source": "crossref", "error": str(e)}, status=500
#         )
# 
# 
# @require_http_methods(["GET"])
# def api_search_crossref_local(request):
#     """API endpoint for CrossRef Local (NAS SQLite database) search."""
#     query = request.GET.get("q", "").strip()
#     max_results = min(int(request.GET.get("max_results", 100)), 1000)
#     ignore_cache = request.GET.get("ignore_cache", "").lower() == "true"
# 
#     if not query:
#         return JsonResponse({"error": "Query parameter required"}, status=400)
# 
#     # Check cache (shorter TTL for local service)
#     cache_key = f"crossref_local_search_{hashlib.md5(f'{query}_{max_results}'.encode()).hexdigest()}"
#     if not ignore_cache:
#         cached = cache.get(cache_key)
#         if cached:
#             cached["cached"] = True
#             return JsonResponse(cached)
# 
#     try:
#         from django.conf import settings
#         import os
# 
#         # Check if CrossRef Local is available
#         crossref_url = getattr(settings, 'CROSSREF_INTERNAL_URL', None)
#         if not crossref_url:
#             crossref_url = os.environ.get('CROSSREF_INTERNAL_URL')
# 
#         if not crossref_url:
#             # Service not configured - return gracefully
#             return JsonResponse(
#                 {
#                     "status": "success",
#                     "source": "crossref_local",
#                     "query": query,
#                     "count": 0,
#                     "results": [],
#                     "note": "CrossRef Local database not available in this environment",
#                 }
#             )
# 
#         # Proxy to internal CrossRef service
#         url = f"{crossref_url}/api/search/"
#         params = {"title": query, "limit": max_results}
# 
#         response = requests.get(url, params=params, timeout=10)
#         response.raise_for_status()
#         data = response.json()
# 
#         # Convert to standard format
#         results = []
# 
#         # Import OA detection if available
#         try:
#             from scitex.scholar.core import detect_oa_from_identifiers
#             oa_detect_available = True
#         except ImportError:
#             oa_detect_available = False
# 
#         for item in data.get("results", []):
#             title = (item.get("title") or "").strip()
#             # Skip papers without titles
#             if not title:
#                 continue
#             doi = item.get("doi") or ""
#             journal = item.get("journal") or ""
# 
#             # Use stored is_open_access if available from local DB
#             is_open_access = item.get("is_open_access", False)
# 
#             # If not set, try to detect from journal name or doi
#             if not is_open_access and oa_detect_available:
#                 try:
#                     oa_result = detect_oa_from_identifiers(doi=doi, journal=journal)
#                     is_open_access = oa_result.is_open_access
#                 except Exception:
#                     pass
# 
#             # Get impact factor for journal
#             impact_factor = item.get("impact_factor") or (get_journal_impact_factor(journal) if journal else None)
# 
#             results.append({
#                 "title": title,
#                 "authors": item.get("authors") or "",
#                 "year": item.get("year"),
#                 "journal": journal,
#                 "doi": doi,
#                 "citations": item.get("citation_count", 0),
#                 "abstract": "",
#                 "externalUrl": f"https://doi.org/{doi}" if doi else "",
#                 "source": "crossref_local",
#                 "is_open_access": is_open_access,
#                 "impact_factor": impact_factor,
#             })
# 
#         from .config import get_limit_for_source
#         result_count = len(results)
#         configured_max = get_limit_for_source("crossref_local", request.user if request.user.is_authenticated else None)
# 
#         response_data = {
#             "status": "success",
#             "source": "crossref_local",
#             "query": query,
#             "count": result_count,
#             "results": results,
#             "result_guidance": _build_result_guidance(
#                 source_name="crossref_local",
#                 received=result_count,
#                 requested=max_results,
#                 configured_max=configured_max,
#             ),
#         }
#         cache.set(cache_key, response_data, 600)  # 10 min cache for local service
#         return JsonResponse(response_data)
#     except requests.exceptions.ConnectionError:
#         # Service not running - return gracefully
#         logger.warning("CrossRef Local service not available")
#         return JsonResponse(
#             {
#                 "status": "success",
#                 "source": "crossref_local",
#                 "query": query,
#                 "count": 0,
#                 "results": [],
#                 "note": "CrossRef Local service not running",
#                 "result_guidance": _build_result_guidance(
#                     source_name="crossref_local",
#                     received=0,
#                     requested=max_results,
#                     configured_max=1000,
#                     error="Service not running",
#                 ),
#             }
#         )
#     except Exception as e:
#         logger.error(f"CrossRef Local search failed: {e}")
#         return JsonResponse(
#             {"status": "error", "source": "crossref_local", "error": str(e)}, status=500
#         )
# 
# 
# @require_http_methods(["GET"])
# def api_search_openalex(request):
#     """API endpoint for OpenAlex search."""
#     query = request.GET.get("q", "").strip()
#     max_results = min(int(request.GET.get("max_results", 50)), 100)
#     ignore_cache = request.GET.get("ignore_cache", "").lower() == "true"
# 
#     if not query:
#         return JsonResponse({"error": "Query parameter required"}, status=400)
# 
#     # Check cache
#     cache_key = f"openalex_search_{hashlib.md5(f'{query}_{max_results}'.encode()).hexdigest()}"
#     if not ignore_cache:
#         cached = cache.get(cache_key)
#         if cached:
#             cached["cached"] = True
#             return JsonResponse(cached)
# 
#     try:
#         # OpenAlex API: https://api.openalex.org/works
#         url = "https://api.openalex.org/works"
#         params = {
#             "search": query,
#             "per-page": max_results,
#             "select": "id,doi,title,authorships,publication_year,primary_location,cited_by_count,abstract_inverted_index,open_access",
#         }
#         headers = {
#             "User-Agent": "SciTeX/1.0 (https://scitex.ai; mailto:contact@scitex.ai)"
#         }
# 
#         response = requests.get(url, params=params, headers=headers, timeout=30)
#         response.raise_for_status()
#         data = response.json()
# 
#         results = []
#         for item in data.get("results", []):
#             # Format authors
#             authors = []
#             for authorship in item.get("authorships", []):
#                 author = authorship.get("author", {})
#                 name = author.get("display_name", "")
#                 if name:
#                     authors.append(name)
# 
#             # Reconstruct abstract from inverted index
#             abstract = ""
#             abstract_idx = item.get("abstract_inverted_index")
#             if abstract_idx:
#                 try:
#                     words = [""] * (max(max(positions) for positions in abstract_idx.values()) + 1)
#                     for word, positions in abstract_idx.items():
#                         for pos in positions:
#                             words[pos] = word
#                     abstract = " ".join(words)
#                 except (ValueError, TypeError):
#                     abstract = ""
# 
#             # Get journal from primary location
#             journal = ""
#             primary_loc = item.get("primary_location") or {}
#             if primary_loc and primary_loc.get("source"):
#                 journal = primary_loc["source"].get("display_name", "") or ""
# 
#             # Clean DOI
#             doi = item.get("doi") or ""
#             if doi.startswith("https://doi.org/"):
#                 doi = doi.replace("https://doi.org/", "")
# 
#             # Handle title - ensure it's never None and skip papers without titles
#             title = (item.get("title") or "").strip()
#             if not title:
#                 continue
# 
#             # Get impact factor for journal
#             impact_factor = get_journal_impact_factor(journal) if journal else None
# 
#             results.append({
#                 "title": title,
#                 "authors": ", ".join(authors[:5]) + ("..." if len(authors) > 5 else ""),
#                 "year": item.get("publication_year"),
#                 "journal": journal,
#                 "doi": doi,
#                 "citations": item.get("cited_by_count", 0),
#                 "abstract": abstract[:500] + "..." if len(abstract) > 500 else abstract,
#                 "is_open_access": item.get("open_access", {}).get("is_oa", False),
#                 "externalUrl": f"https://doi.org/{doi}" if doi else "",
#                 "source": "openalex",
#                 "impact_factor": impact_factor,
#             })
# 
#         from .config import get_limit_for_source
#         result_count = len(results)
#         configured_max = get_limit_for_source("openalex", request.user if request.user.is_authenticated else None)
# 
#         response_data = {
#             "status": "success",
#             "source": "openalex",
#             "query": query,
#             "count": result_count,
#             "results": results,
#             "result_guidance": _build_result_guidance(
#                 source_name="openalex",
#                 received=result_count,
#                 requested=max_results,
#                 configured_max=configured_max,
#             ),
#         }
#         cache.set(cache_key, response_data, 1800)
#         return JsonResponse(response_data)
#     except Exception as e:
#         logger.error(f"OpenAlex API search failed: {e}")
#         return JsonResponse(
#             {"status": "error", "source": "openalex", "error": str(e)}, status=500
#         )
# 
# 
# # =============================================================================
# # Unified RESTful Search API with Command Syntax Support
# # =============================================================================
# 
# from concurrent.futures import ThreadPoolExecutor, as_completed
# from .search_helpers import parse_query_operators, apply_advanced_filters
# from ...middleware.rate_limit import rate_limit, rate_limit_status
# from ...api_auth import api_key_optional
# from .config import get_limit_for_source
# 
# 
# def _explain_result_count(source_name, received, requested, error=None):
#     """
#     Explain why a source returned a specific number of results.
# 
#     Args:
#         source_name: Name of the search source
#         received: Number of results actually received
#         requested: Number of results requested
#         error: Error message if any
# 
#     Returns:
#         String explanation for users
#     """
#     if error:
#         return f"Error occurred: {error}"
# 
#     if received == 0:
#         return "No matching results found in this source"
# 
#     if received < requested:
#         reasons = []
# 
#         # Source-specific explanations
#         if source_name == "crossref":
#             reasons.append("CrossRef API has strict rate limits")
#             if received < 10:
#                 reasons.append("Limited results may indicate rate limiting or narrow query match")
#         elif source_name == "crossref_local":
#             reasons.append("Local database query - no rate limits")
#             if received == 0:
#                 reasons.append("Database may not be populated or query doesn't match local data")
#         elif source_name == "semantic":
#             reasons.append("Semantic Scholar has aggressive rate limiting (10 results max)")
#         elif source_name == "pubmed":
#             if received < requested / 2:
#                 reasons.append("PubMed API may be rate limiting or query is very specific")
#         elif source_name == "openalex":
#             if received == 50:
#                 reasons.append("Default limit reached (50 results)")
# 
#         # Generic explanations
#         if received < 5:
#             reasons.append("Very few matches - try broader search terms")
#         elif received < requested / 2:
#             reasons.append("API returned fewer results than requested")
#         else:
#             reasons.append(f"Source returned {received}/{requested} requested results")
# 
#         return " | ".join(reasons)
# 
#     return f"Received all {received} requested results"
# 
# # Import scitex.scholar integration (preferred for core logic)
# from ...integrations import scitex_scholar as scitex_integration
# 
# 
# @api_key_optional
# @rate_limit("api_search_unified")
# @require_http_methods(["GET"])
# def api_search_unified(request):
#     """
#     Unified RESTful API for academic literature search.
# 
#     Supports shell-style command syntax for filtering:
#     - `-t VALUE` or `--title VALUE`: Title filter (include)
#     - `-t -VALUE`: Title filter (exclude)
#     - `-a VALUE` or `--author VALUE`: Author filter
#     - `-j VALUE` or `--journal VALUE`: Journal filter
#     - `-ymin YYYY` or `--year-min`: Minimum year
#     - `-ymax YYYY` or `--year-max`: Maximum year
#     - `-cmin N` or `--citations-min`: Minimum citations
#     - `-cmax N` or `--citations-max`: Maximum citations
#     - `-ifmin N` or `--if-min`: Minimum impact factor
#     - `-ifmax N` or `--if-max`: Maximum impact factor
# 
#     Query Parameters:
#     - q (required): Search query with optional command syntax
#     - sources: Comma-separated list of sources (default: all available)
#                Options: pubmed,arxiv,semantic,crossref,openalex,pmc,doaj,biorxiv,plos
#     - max_results: Maximum results per source (default: 20, max: 100)
#     - format: Response format - 'full' or 'compact' (default: full)
# 
#     Example:
#         GET /scholar/api/search/?q=neural network -t deep learning -a Smith -ymin 2020 -cmin 50
#         GET /scholar/api/search/?q=CRISPR&sources=pubmed,arxiv&max_results=50
# 
#     Returns:
#         JSON response with aggregated search results from all sources.
#     """
#     query = request.GET.get("q", "").strip()
#     if not query:
#         return JsonResponse({
#             "status": "error",
#             "error": "Query parameter 'q' is required",
#             "syntax_help": {
#                 "title_filter": "-t VALUE (include) or -t -VALUE (exclude)",
#                 "author_filter": "-a VALUE or --author VALUE",
#                 "journal_filter": "-j VALUE or --journal VALUE",
#                 "year_range": "-ymin YYYY -ymax YYYY",
#                 "citations_min": "-cmin N",
#                 "impact_factor_min": "-ifmin N",
#                 "example": "neural network -t deep learning -a Smith -ymin 2020"
#             }
#         }, status=400)
# 
#     # Get max results and format options
#     try:
#         max_results = min(int(request.GET.get("max_results", 20)), 100)
#     except ValueError:
#         max_results = 20
#     response_format = request.GET.get("format", "full").lower()
#     use_scitex = request.GET.get("engine", "auto").lower() != "django"
# 
#     # Try to use scitex.scholar if available (preferred - reuses local logic)
#     if use_scitex and scitex_integration.is_available():
#         try:
#             # Use scitex.scholar's advanced query parser and search engine
#             scitex_results = scitex_integration.search_sync(
#                 query=query,
#                 mode='parallel',
#                 max_results=max_results,
#                 email=getattr(request.user, 'email', None) if request.user.is_authenticated else None,
#             )
# 
#             # Convert to Django-compatible format
#             formatted_results = scitex_integration.convert_scitex_results_to_django(scitex_results)
# 
#             # Get parsed filters from scitex
#             parsed = scitex_integration.parse_query_scitex(query)
# 
#             # Build result guidance from scitex metadata
#             source_metadata = scitex_results.get("metadata", {}).get("sources", {})
#             total_before_dedup = sum(
#                 meta.get("result_count", 0) for meta in source_metadata.values()
#             )
#             deduplication_count = total_before_dedup - len(formatted_results)
# 
#             result_guidance = {
#                 "total_fetched": total_before_dedup,
#                 "total_after_dedup": len(formatted_results),
#                 "deduplication": {
#                     "removed": deduplication_count,
#                     "explanation": "Duplicate papers (same DOI/title) removed across sources"
#                 },
#                 "per_source_limits": {
#                     source: {
#                         "requested": max_results,
#                         "received": meta.get("result_count", 0),
#                         "configured_max": get_limit_for_source(source, request.user),
#                         "reason": _explain_result_count(
#                             source,
#                             meta.get("result_count", 0),
#                             max_results,
#                             meta.get("error")
#                         )
#                     }
#                     for source, meta in source_metadata.items()
#                 },
#                 "rate_limiting": {
#                     "applied": True,
#                     "details": rate_limit_status(request, "api_search_unified"),
#                     "explanation": "Rate limits protect external APIs and ensure service stability"
#                 }
#             }
# 
#             return JsonResponse({
#                 "status": "success",
#                 "engine": "scitex.scholar",
#                 "query": {
#                     "original": query,
#                     "parsed": parsed.get("keyword_query", query),
#                     "filters": {
#                         "positive_keywords": parsed.get("positive_keywords", []),
#                         "negative_keywords": parsed.get("negative_keywords", []),
#                         "year_start": parsed.get("year_start"),
#                         "year_end": parsed.get("year_end"),
#                         "min_citations": parsed.get("min_citations"),
#                         "max_citations": parsed.get("max_citations"),
#                         "min_impact_factor": parsed.get("min_impact_factor"),
#                         "max_impact_factor": parsed.get("max_impact_factor"),
#                         "open_access": parsed.get("open_access"),
#                     }
#                 },
#                 "sources": scitex_results.get("metadata", {}).get("sources", {}),
#                 "total_count": len(formatted_results),
#                 "results": formatted_results if response_format == "full" else [
#                     {k: r[k] for k in ["title", "authors", "year", "journal", "doi", "citations", "source"] if k in r}
#                     for r in formatted_results
#                 ],
#                 "stats": scitex_results.get("stats", {}),
#                 "rate_limit": rate_limit_status(request, "api_search_unified"),
#                 "result_guidance": result_guidance,
#             })
# 
#         except Exception as e:
#             logger.warning(f"scitex.scholar search failed, falling back to Django: {e}")
#             # Fall through to Django implementation
# 
#     # Fallback: Django-only implementation
#     # Parse command syntax from query
#     parsed = parse_query_operators(query)
#     clean_query = parsed.get("query", query)
# 
#     # Get sources to search
#     sources_param = request.GET.get("sources", "").strip()
#     available_sources = {
#         "pubmed": search_pubmed,
#         "arxiv": search_arxiv,
#         "semantic": search_semantic_scholar,
#         "pmc": search_pubmed_central,
#         "doaj": search_doaj,
#         "biorxiv": search_biorxiv,
#         "plos": search_plos,
#     }
# 
#     if sources_param:
#         requested_sources = [s.strip().lower() for s in sources_param.split(",")]
#         sources_to_search = {k: v for k, v in available_sources.items() if k in requested_sources}
#     else:
#         # Default to main sources for performance
#         sources_to_search = {
#             "pubmed": search_pubmed,
#             "arxiv": search_arxiv,
#             "semantic": search_semantic_scholar,
#         }
# 
#     # Search all sources in parallel
#     all_results = []
#     source_stats = {}
#     errors = []
# 
#     def search_source(name, search_func):
#         try:
#             results = search_func(clean_query, max_results=max_results)
#             return name, results, None
#         except Exception as e:
#             return name, [], str(e)
# 
#     with ThreadPoolExecutor(max_workers=len(sources_to_search)) as executor:
#         futures = {
#             executor.submit(search_source, name, func): name
#             for name, func in sources_to_search.items()
#         }
# 
#         for future in as_completed(futures):
#             source_name, results, error = future.result()
#             if error:
#                 errors.append({"source": source_name, "error": error})
#                 source_stats[source_name] = {"count": 0, "status": "error"}
#             else:
#                 source_stats[source_name] = {"count": len(results), "status": "success"}
#                 all_results.extend(results)
# 
#     # Apply filters from parsed operators
#     filtered_results = apply_advanced_filters(all_results, None, parsed)
# 
#     # Sort by citations (descending), then by year (descending)
#     filtered_results.sort(
#         key=lambda x: (
#             -(x.get("citations") or 0),
#             -(int(x.get("year") or 0))
#         )
#     )
# 
#     # Format response
#     if response_format == "compact":
#         # Compact format - only essential fields
#         formatted_results = [
#             {
#                 "title": r.get("title"),
#                 "authors": r.get("authors"),
#                 "year": r.get("year"),
#                 "journal": r.get("journal"),
#                 "doi": r.get("doi"),
#                 "citations": r.get("citations"),
#                 "source": r.get("source"),
#             }
#             for r in filtered_results
#         ]
#     else:
#         formatted_results = filtered_results
# 
#     # Calculate deduplication stats
#     total_before_dedup = sum(stats.get("count", 0) for stats in source_stats.values())
#     deduplication_count = total_before_dedup - len(filtered_results)
# 
#     # Build result guidance
#     result_guidance = {
#         "total_fetched": total_before_dedup,
#         "total_after_dedup": len(filtered_results),
#         "deduplication": {
#             "removed": deduplication_count,
#             "explanation": "Duplicate papers (same DOI/title) removed across sources"
#         },
#         "per_source_limits": {
#             source: {
#                 "requested": max_results,
#                 "received": stats.get("count", 0),
#                 "configured_max": get_limit_for_source(source, request.user),
#                 "reason": _explain_result_count(source, stats.get("count", 0), max_results, stats.get("error"))
#             }
#             for source, stats in source_stats.items()
#         },
#         "rate_limiting": {
#             "applied": True,
#             "details": rate_limit_status(request, "api_search_unified"),
#             "explanation": "Rate limits protect external APIs and ensure service stability"
#         }
#     }
# 
#     return JsonResponse({
#         "status": "success",
#         "engine": "django",
#         "query": {
#             "original": query,
#             "parsed": clean_query,
#             "filters": {
#                 "title_includes": parsed.get("title_includes", []),
#                 "title_excludes": parsed.get("title_excludes", []),
#                 "author_includes": parsed.get("author_includes", []),
#                 "author_excludes": parsed.get("author_excludes", []),
#                 "journal_includes": parsed.get("journal_includes", []),
#                 "journal_excludes": parsed.get("journal_excludes", []),
#                 "year_min": parsed.get("year_min"),
#                 "year_max": parsed.get("year_max"),
#                 "citations_min": parsed.get("citations_min"),
#                 "citations_max": parsed.get("citations_max"),
#                 "impact_factor_min": parsed.get("impact_factor_min"),
#                 "impact_factor_max": parsed.get("impact_factor_max"),
#             }
#         },
#         "sources": source_stats,
#         "total_count": len(filtered_results),
#         "results": formatted_results,
#         "errors": errors if errors else None,
#         "rate_limit": rate_limit_status(request, "api_search_unified"),
#         "result_guidance": result_guidance,
#     })
# 
# 
# @require_http_methods(["GET"])
# def api_search_syntax_help(request):
#     """
#     API endpoint to get search syntax documentation.
# 
#     Returns detailed documentation on available search operators and examples.
#     """
#     return JsonResponse({
#         "status": "success",
#         "syntax": {
#             "title_filter": {
#                 "short": "-t",
#                 "long": "--title",
#                 "description": "Filter by title content",
#                 "include_example": "-t neural",
#                 "exclude_example": "-t -mouse",
#             },
#             "author_filter": {
#                 "short": "-a",
#                 "long": "--author",
#                 "description": "Filter by author name",
#                 "include_example": "-a Smith",
#                 "exclude_example": "-a -Jones",
#             },
#             "journal_filter": {
#                 "short": "-j",
#                 "long": "--journal",
#                 "description": "Filter by journal name",
#                 "include_example": "-j Nature",
#                 "exclude_example": "-j -arXiv",
#             },
#             "year_min": {
#                 "short": "-ymin",
#                 "long": "--year-min",
#                 "description": "Minimum publication year",
#                 "example": "-ymin 2020",
#             },
#             "year_max": {
#                 "short": "-ymax",
#                 "long": "--year-max",
#                 "description": "Maximum publication year",
#                 "example": "-ymax 2024",
#             },
#             "citations_min": {
#                 "short": "-cmin",
#                 "long": "--citations-min",
#                 "description": "Minimum citation count",
#                 "example": "-cmin 100",
#             },
#             "citations_max": {
#                 "short": "-cmax",
#                 "long": "--citations-max",
#                 "description": "Maximum citation count",
#                 "example": "-cmax 1000",
#             },
#             "impact_factor_min": {
#                 "short": "-ifmin",
#                 "long": "--if-min",
#                 "description": "Minimum journal impact factor",
#                 "example": "-ifmin 5",
#             },
#             "impact_factor_max": {
#                 "short": "-ifmax",
#                 "long": "--if-max",
#                 "description": "Maximum journal impact factor",
#                 "example": "-ifmax 50",
#             },
#         },
#         "examples": [
#             {
#                 "query": "neural network -t deep learning -ymin 2020",
#                 "description": "Search for 'neural network', title must contain 'deep learning', published since 2020"
#             },
#             {
#                 "query": "CRISPR -a Doudna -j Nature -cmin 100",
#                 "description": "Search for 'CRISPR' by author Doudna in Nature journal with at least 100 citations"
#             },
#             {
#                 "query": "cancer treatment -t -mouse -t -rat -ymin 2022",
#                 "description": "Search for 'cancer treatment', exclude mouse and rat studies, since 2022"
#             },
#             {
#                 "query": "machine learning -ifmin 10 -cmin 50",
#                 "description": "Search 'machine learning' in journals with IF ≥ 10 and papers with ≥ 50 citations"
#             },
#         ],
#         "available_sources": [
#             "pubmed", "arxiv", "semantic", "crossref", "openalex",
#             "pmc", "doaj", "biorxiv", "plos"
#         ],
#         "query_parameters": {
#             "q": "Search query with optional command syntax (required)",
#             "sources": "Comma-separated list of sources to search (optional)",
#             "max_results": "Maximum results per source, 1-100 (default: 20)",
#             "format": "'full' or 'compact' response format (default: full)",
#         }
#     })
# 

# --------------------------------------------------------------------------------
# End of Source Code from: apps/scholar_app/views/search/api_search.py
# --------------------------------------------------------------------------------
