# Generated by Django 5.2.11 on 2026-02-22 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project_app", "0025_add_issue_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60)),
                ("label", models.CharField(max_length=100)),
                ("source_code", models.TextField()),
                ("icon", models.CharField(default="fa-puzzle-piece", max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("writing", "Writing"),
                            ("visualization", "Visualization"),
                            ("data", "Data"),
                            ("analysis", "Analysis"),
                            ("reference", "Reference"),
                            ("utility", "Utility"),
                            ("other", "Other"),
                        ],
                        default="utility",
                        max_length=30,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                ("version", models.CharField(default="0.1.0", max_length=20)),
                ("dependencies", models.JSONField(default=list)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("group", "Group"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("run_count", models.PositiveIntegerField(default=0)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_modules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shared_user_modules",
                        to="project_app.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Module",
                "ordering": ["-updated_at"],
                "unique_together": {("author", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ModuleExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("wall_time_ms", models.PositiveIntegerField(default=0)),
                ("peak_memory_mb", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("output_json", models.JSONField(default=list)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="module_executions",
                        to="project_app.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="modulemaker_app.usermodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Execution",
                "ordering": ["-started_at"],
            },
        ),
    ]
