# Generated by Django 5.2.11 on 2026-02-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulemaker_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodule",
            name="source_repo_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Branch, tag, or commit hash",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="usermodule",
            name="source_repo_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
