# Generated by Django 5.2.11 on 2026-02-14 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_app', '0002_alter_integrationconnection_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, help_text='Event type (e.g., test_complete)', max_length=50)),
                ('project', models.CharField(db_index=True, help_text='Project name', max_length=100)),
                ('status', models.CharField(help_text='success or failure', max_length=20)),
                ('payload', models.JSONField(default=dict, help_text='Event-specific data')),
                ('source', models.CharField(default='local', help_text='Origin: local, hpc, ci', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'type', '-created_at'], name='integration_user_id_76129f_idx')],
            },
        ),
    ]
