// status.scitex.ai — user-facing copy, en + ja.
//
// SPLIT OUT OF worker.js on 2026-08-05: it was the part that kept pushing that
// file over the 512-line limit — ~170 lines that grow whenever any section gains
// a label, with nothing to do with probing or rendering. Pure data module: no
// imports, no side effects.
//
// STRINGS THAT INTERPOLATE A NUMBER ARE FUNCTIONS, not templates baked against a
// constant. `recheck` used to close over worker.js CACHE_SECONDS; keeping that
// would make this module import from the file it was extracted from, which is a
// cycle. The caller passes the value instead — the shape `someDown` already had.

export const T = {
  en: {
    title: "SciTeX Status",
    allUp: "All systems operational",
    someDown: (n) => `${n} service${n === 1 ? "" : "s"} down`,
    allDown: "All systems down",
    colService: "Service",
    colState: "State",
    colResponse: "Response",
    colTime: "Time",
    up: "Operational",
    down: "Down",
    unreachable: "unreachable",
    checked: "Last checked",
    recheck: (n) => `re-checked every ${n}s`,
    edge: "This page runs on Cloudflare and stays available even when SciTeX servers are down.",
    internals: "Internal metrics",
    internalsMissing:
      "The hub status API did not respond, so internal metrics are unavailable. The checks above are measured from outside and are unaffected.",
    internalsSchema:
      "The hub status API answered in a format this page does not know how to read, so nothing is shown rather than something wrong. Schema",
    internalsEmpty:
      "The hub status API answered but reported no readings at all.",
    partial:
      "Some hub checks did not answer within the deadline. They are shown as UNKNOWN below — not as working, and not as broken.",
    measuredAt: "Internals measured at",
    unavailable: "unavailable",
    system: "System resources",
    cpu: "CPU",
    memory: "Memory",
    disk: "Disk",
    gpu: "GPU",
    diskIo: "Disk I/O (total)",
    netIo: "Network I/O (total)",
    users: "Users",
    registered: "registered (visitors excluded)",
    cores: "cores",
    logical: "logical",
    available: "available",
    used: "used",
    none: "None available",
    containers: "Containers",
    apis: "Internal APIs",
    ssh: "SSH services",
    stores: "Data stores",
    compute: "Compute",
    orgs: "Git organisations",
    packages: "Package versions",
    visitors: "Visitor pool",
    colDetail: "Detail",
    colOrg: "Organisation",
    colPackage: "Package",
    colVersion: "Version",
    colSlot: "Slot",
    slot: "Slot",
    allocated: "In use",
    free: "Free",
    expiresIn: "expires in",
    minutes: "min",
    slotsAllocated: "slots in use",
    djangoRecordMissing: "Django record missing",
    timeline: "History",
    timelineUnbound:
      "History storage is not attached to this Worker, so no timeline can be shown. The live checks above are unaffected.",
    timelineError:
      "History storage could not be read, so the timeline is not shown rather than shown incomplete.",
    timelineSchema:
      "History storage answered in a format this page does not know how to read, so nothing is shown rather than something wrong.",
    timelineEmpty:
      "No history recorded yet. The recorder samples every 5 minutes; the first full day appears tomorrow.",
    noData: "no data",
    samples: "samples",
    ongoing: "Ongoing",
    resolved: "Resolved",
    noIncidents: "No incidents recorded in the retained window.",
    colStarted: "Started (UTC)",
    colDuration: "Duration",
    colAffected: "Affected",
    stripAria: "Daily availability, oldest day on the left",
    overDays: (n) => `over ${n} measured day${n === 1 ? "" : "s"}`,
    unmeasured: (n) => `${n} day${n === 1 ? "" : "s"} not measured`,
    hours: "h",
    other: "日本語",
  },
  ja: {
    title: "SciTeX ステータス",
    allUp: "すべて稼働中",
    someDown: (n) => `${n} 件が停止`,
    allDown: "全システム停止",
    colService: "サービス",
    colState: "状態",
    colResponse: "応答",
    colTime: "時間",
    up: "稼働中",
    down: "停止",
    unreachable: "到達不可",
    checked: "最終確認",
    recheck: (n) => `${n} 秒ごとに再確認します`,
    edge: "このページは Cloudflare 上で動作しており、SciTeX の各サーバーが停止していても表示され続けます。",
    internals: "内部メトリクス",
    internalsMissing:
      "本体のステータス API が応答しなかったため、内部メトリクスは取得できていません。上の項目は外部から測定しているので影響を受けません。",
    internalsSchema:
      "本体のステータス API の応答形式をこのページが解釈できませんでした。誤った値を出すより何も出さない方が安全なため、表示していません。スキーマ",
    internalsEmpty:
      "本体のステータス API は応答しましたが、値がありませんでした。",
    partial:
      "一部のチェックが制限時間内に応答しませんでした。下では「不明」と表示しています（正常でも異常でもありません）。",
    measuredAt: "内部測定時刻",
    unavailable: "取得不可",
    system: "システムリソース",
    cpu: "CPU",
    memory: "メモリ",
    disk: "ディスク",
    gpu: "GPU",
    diskIo: "ディスク I/O（累計）",
    netIo: "ネットワーク I/O（累計）",
    users: "ユーザー",
    registered: "登録済み（訪問者を除く）",
    cores: "コア",
    logical: "論理",
    available: "利用可能",
    used: "使用",
    none: "なし",
    containers: "コンテナ",
    apis: "内部 API",
    ssh: "SSH サービス",
    stores: "データストア",
    compute: "計算基盤",
    orgs: "Git 組織",
    packages: "パッケージ版数",
    visitors: "訪問者スロット",
    colDetail: "詳細",
    colOrg: "組織",
    colPackage: "パッケージ",
    colVersion: "バージョン",
    colSlot: "スロット",
    slot: "スロット",
    allocated: "使用中",
    free: "空き",
    expiresIn: "残り",
    minutes: "分",
    slotsAllocated: "スロット使用中",
    djangoRecordMissing: "Django レコードなし",
    timeline: "履歴",
    timelineUnbound:
      "履歴の保存先がこの Worker に接続されていないため、タイムラインを表示できません。上のリアルタイム確認には影響しません。",
    timelineError:
      "履歴の保存先を読み取れませんでした。不完全な履歴を出すより表示しない方が安全なため、非表示にしています。",
    timelineSchema:
      "履歴の保存先の形式をこのページが解釈できませんでした。誤った値を出すより何も出さない方が安全なため、表示していません。",
    timelineEmpty:
      "まだ履歴がありません。5 分ごとに記録しており、丸一日分は翌日に表示されます。",
    noData: "記録なし",
    samples: "件",
    ongoing: "継続中",
    resolved: "復旧済み",
    noIncidents: "保持期間内に障害の記録はありません。",
    colStarted: "開始（UTC）",
    colDuration: "継続時間",
    colAffected: "影響範囲",
    stripAria: "日ごとの稼働率。左が古い日です",
    overDays: (n) => `測定できた ${n} 日間`,
    unmeasured: (n) => `${n} 日は未測定`,
    hours: "時間",
    other: "English",
  },
};
