# Generated by Django 5.2.11 on 2026-02-27 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0026_add_is_home_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="app_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="App category for marketplace listing",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="app_license",
            field=models.CharField(
                blank=True,
                default="AGPL-3.0",
                help_text="SPDX license identifier for app distribution",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="app_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="app_reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_apps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="app_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                help_text="Marketplace submission status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="app_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_app",
            field=models.BooleanField(
                default=False,
                help_text="Whether this project has been submitted as a marketplace app",
            ),
        ),
    ]
