# Generated by Django 5.2.11 on 2026-02-19 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("console_app", "0003_userquota"),
        ("project_app", "0025_add_issue_template"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="codeexecutionjob",
            new_name="console_app_user_id_010fb7_idx",
            old_name="code_app_co_user_id_a8fbc3_idx",
        ),
        migrations.RenameIndex(
            model_name="codeexecutionjob",
            new_name="console_app_created_057b1e_idx",
            old_name="code_app_co_created_7321f1_idx",
        ),
        migrations.RenameIndex(
            model_name="projectservice",
            new_name="console_app_project_21dcb3_idx",
            old_name="code_app_pr_project_f0648e_idx",
        ),
        migrations.RenameIndex(
            model_name="projectservice",
            new_name="console_app_port_7cd8b1_idx",
            old_name="code_app_pr_port_5d50ec_idx",
        ),
        migrations.RenameIndex(
            model_name="projectservice",
            new_name="console_app_last_ac_e2a6fc_idx",
            old_name="code_app_pr_last_ac_e1fc44_idx",
        ),
        migrations.RenameIndex(
            model_name="resourceusage",
            new_name="console_app_user_id_bab55c_idx",
            old_name="code_app_re_user_id_434016_idx",
        ),
        migrations.RenameIndex(
            model_name="resourceusage",
            new_name="console_app_date_4d3ab0_idx",
            old_name="code_app_re_date_d156e2_idx",
        ),
        migrations.AlterUniqueTogether(
            name="projectservice",
            unique_together={("project", "port")},
        ),
    ]
