# Generated by Django 5.2.11 on 2026-02-19 23:46
# NOTE: Index renames removed - migrations 0001/0002 now use correct names directly.
# Only AlterUniqueTogether is kept as it's not index-name dependent.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("console_app", "0003_userquota"),
        ("project_app", "0025_add_issue_template"),
    ]

    operations = [
        # RenameIndex operations removed - indexes already have correct names
        migrations.AlterUniqueTogether(
            name="projectservice",
            unique_together={("project", "port")},
        ),
    ]
